User.create!(
  email: 'test@test.com',
  password: '123456',
  first_name: '将暉',
  first_name_kana: 'マサキ',
  last_name: '菅田',
  last_name_kana: 'スダ',
  phone_number: '09012345678',
  birthday: '1993-02-21', 
  sex: 'male',
  height: '176',
  weight: '65',
)

foods = Food.create!([
  {
    name: '白ご飯（白米・100g）',
    kcal: '168',
    protein: '3',
    lipid: '0',
    carbo: '37',
  },
  {
    name: '白ご飯（白米・120g）',
    kcal: '202',
    protein: '3',
    lipid: '0',
    carbo: '45',
  },
  {
    name: '白ご飯（白米・150g）',
    kcal: '252',
    protein: '4',
    lipid: '1',
    carbo: '56',
  },
  {
    name: '白ご飯（白米・180g）',
    kcal: '302',
    protein: '5',
    lipid: '1',
    carbo: '67',
  },
  {
    name: '白ご飯（白米・ 200g）',
    kcal: '336',
    protein: '5',
    lipid: '1',
    carbo: '74',
  },
  {
    name: '白ご飯（白米・ 300g）',
    kcal: '504',
    protein: '8',
    lipid: '1',
    carbo: '111',
  },
  {
    name: '玄米ご飯（100g）',
    kcal: '158',
    protein: '3',
    lipid: '1',
    carbo: '34',
  },
  {
    name: '玄米ご飯（120g）',
    kcal: '198',
    protein: '3',
    lipid: '1',
    carbo: '42',
  },
  {
    name: '玄米ご飯（150g）',
    kcal: '257',
    protein: '4',
    lipid: '2',
    carbo: '56',
  },
  {
    name: '玄米ご飯（180g）',
    kcal: '297',
    protein: '5',
    lipid: '2',
    carbo: '64',
  },
  {
    name: '玄米ご飯（200g）',
    kcal: '337',
    protein: '6',
    lipid: '2',
    carbo: '73',
  },
  {
    name: '玄米ご飯（300g）',
    kcal: '495',
    protein: '9',
    lipid: '3',
    carbo: '107',
  },
  {
    name: 'おにぎり（サケ）',
    kcal: '191',
    protein: '6',
    lipid: '1',
    carbo: '38',
  },
  {
    name: 'おにぎり（梅）',
    kcal: '173',
    protein: '3',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（昆布）',
    kcal: '195',
    protein: '4',
    lipid: '1',
    carbo: '43',
  },
  {
    name: 'おにぎり（ツナマヨ）',
    kcal: '240',
    protein: '5',
    lipid: '7',
    carbo: '38',
  },
  {
    name: 'おにぎり（エビマヨ）',
    kcal: '206',
    protein: '5',
    lipid: '3',
    carbo: '38',
  },
  {
    name: 'おにぎり（明太子）',
    kcal: '182',
    protein: '5',
    lipid: '1',
    carbo: '38',
  },
  {
    name: 'おにぎり（たらこ）',
    kcal: '187',
    protein: '6',
    lipid: '1',
    carbo: '38',
  },
  {
    name: 'おにぎり（塩）',
    kcal: '168',
    protein: '3',
    lipid: '0',
    carbo: '37',
  },
  {
    name: 'おにぎり（高菜）',
    kcal: '173',
    protein: '3',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（鶏五目）',
    kcal: '240',
    protein: '7',
    lipid: '3',
    carbo: '44',
  },
  {
    name: 'おにぎり（煮たまご）',
    kcal: '222',
    protein: '7',
    lipid: '3',
    carbo: '40',
  },
  {
    name: 'おにぎり（おかか）',
    kcal: '176',
    protein: '4',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（梅しそひじき）',
    kcal: '172',
    protein: '3',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（ねぎとろ）',
    kcal: '224',
    protein: '6',
    lipid: '4',
    carbo: '39',
  },
  {
    name: 'おにぎり（明太子マヨネーズ）',
    kcal: '236',
    protein: '5',
    lipid: '7',
    carbo: '38',
  },
  {
    name: 'おにぎり（牛カルビマヨネーズ）',
    kcal: '342',
    protein: '7',
    lipid: '16',
    carbo: '39',
  },
  {
    name: 'おにぎり（すじこ）',
    kcal: '212',
    protein: '8',
    lipid: '3',
    carbo: '38',
  },
  {
    name: 'おにぎり（天むす）',
    kcal: '218',
    protein: '6',
    lipid: '4',
    carbo: '39',
  },
  {
    name: 'お茶漬け',
    kcal: '274',
    protein: '5',
    lipid: '1',
    carbo: '58',
  },
  {
    name: 'お茶漬け（鯛茶漬け）',
    kcal: '287',
    protein: '8',
    lipid: '2',
    carbo: '57',
  },
  {
    name: 'お茶漬け（うなぎ）',
    kcal: '361',
    protein: '12',
    lipid: '8',
    carbo: '58',
  },
  {
    name: '雑炊',
    kcal: '291',
    protein: '7',
    lipid: '3',
    carbo: '57',
  },
  {
    name: 'たまご雑炊',
    kcal: '290',
    protein: '8',
    lipid: '3',
    carbo: '54',
  },
  {
    name: 'キムチ雑炊',
    kcal: '306',
    protein: '8',
    lipid: '3',
    carbo: '60',
  },
  {
    name: 'カニ雑炊',
    kcal: '360',
    protein: '20',
    lipid: '5',
    carbo: '54',
  },
  {
    name: '親子丼',
    kcal: '673',
    protein: '24',
    lipid: '15',
    carbo: '104',
  },
  {
    name: '海鮮丼',
    kcal: '648',
    protein: '31',
    lipid: '8',
    carbo: '106',
  },
  {
    name: 'カツ丼',
    kcal: '896',
    protein: '31',
    lipid: '34',
    carbo: '110',
  },
  {
    name: '牛丼',
    kcal: '735',
    protein: '22',
    lipid: '20',
    carbo: '105',
  },
  {
    name: '豚丼',
    kcal: '874',
    protein: '19',
    lipid: '41',
    carbo: '99',
  },
  {
    name: 'ビビンバ',
    kcal: '753',
    protein: '17',
    lipid: '28',
    carbo: '102',
  },
  {
    name: 'クッパ',
    kcal: '496',
    protein: '19',
    lipid: '14',
    carbo: '71',
  },
  {
    name: 'ひつまぶし',
    kcal: '674',
    protein: '26',
    lipid: '18',
    carbo: '98',
  },
  {
    name: 'チキンカツ丼',
    kcal: '835',
    protein: '28',
    lipid: '28',
    carbo: '108',
  },
  {
    name: 'いくらご飯',
    kcal: '557',
    protein: '23',
    lipid: '9',
    carbo: '93',
  },
  {
    name: 'チャーシュー丼',
    kcal: '595',
    protein: '14',
    lipid: '11',
    carbo: '102',
  },
  {
    name: '中華丼',
    kcal: '698',
    protein: '19',
    lipid: '19',
    carbo: '107',
  },
  {
    name: '鰻重',
    kcal: '772',
    protein: '31',
    lipid: '23',
    carbo: '104',
  },
  {
    name: '鉄火丼',
    kcal: '547',
    protein: '28',
    lipid: '2',
    carbo: '99',
  },
  {
    name: '天丼',
    kcal: '838',
    protein: '23',
    lipid: '27',
    carbo: '119',
  },
  {
    name: 'イカ天丼',
    kcal: '723',
    protein: '20',
    lipid: '12',
    carbo: '128',
  },
  {
    name: '鶏天丼',
    kcal: '799',
    protein: '32',
    lipid: '18',
    carbo: '120',
  },
  {
    name: 'えび天丼',
    kcal: '703',
    protein: '19',
    lipid: '13',
    carbo: '121',
  },
  {
    name: '鶏マヨ丼',
    kcal: '791',
    protein: '25',
    lipid: '25',
    carbo: '110',
  },
  {
    name: '釜めし',
    kcal: '333',
    protein: '11',
    lipid: '5',
    carbo: '58',
  },
  {
    name: '生しらす丼',
    kcal: '511',
    protein: '25',
    lipid: '2',
    carbo: '93',
  },
  {
    name: '麻婆丼',
    kcal: '732',
    protein: '25',
    lipid: '22',
    carbo: '103',
  },
  {
    name: 'まぐろアボカド丼',
    kcal: '716',
    protein: '28',
    lipid: '20',
    carbo: '101',
  },
  {
    name: 'サーモンアボカド丼',
    kcal: '665',
    protein: '17',
    lipid: '19',
    carbo: '103',
  },
  {
    name: 'まぐろのユッケ丼',
    kcal: '626',
    protein: '27',
    lipid: '14',
    carbo: '92',
  },
  {
    name: 'まぐろ山かけ丼',
    kcal: '549',
    protein: '26',
    lipid: '2',
    carbo: '102',
  },
  {
    name: '味噌かつ丼',
    kcal: '1039',
    protein: '33',
    lipid: '38',
    carbo: '132',
  },
  {
    name: '麦とろご飯',
    kcal: '323',
    protein: '7',
    lipid: '1',
    carbo: '70',
  },
  {
    name: '焼鳥丼',
    kcal: '732',
    protein: '22',
    lipid: '22',
    carbo: '105',
  },
  {
    name: 'すき焼き丼',
    kcal: '664',
    protein: '28',
    lipid: '13',
    carbo: '102',
  },
  {
    name: '焼肉丼',
    kcal: '678',
    protein: '27',
    lipid: '14',
    carbo: '105',
  },
  {
    name: 'ステーキ丼',
    kcal: '890',
    protein: '29',
    lipid: '37',
    carbo: '101',
  },
  {
    name: 'ローストビーフ丼',
    kcal: '686',
    protein: '30',
    lipid: '13',
    carbo: '103',
  },
  {
    name: 'ソースカツ丼',
    kcal: '940',
    protein: '30',
    lipid: '37',
    carbo: '118',
  },
  {
    name: 'ロコモコ',
    kcal: '766',
    protein: '28',
    lipid: '21',
    carbo: '112',
  },
  {
    name: 'ねぎとろ丼',
    kcal: '747',
    protein: '24',
    lipid: '24',
    carbo: '102',
  },
  {
    name: '麻婆なす丼',
    kcal: '677',
    protein: '14',
    lipid: '21',
    carbo: '102',
  },
  {
    name: 'ヒレカツ丼',
    kcal: '797',
    protein: '32',
    lipid: '20',
    carbo: '112',
  },
  {
    name: '味噌汁（わかめと豆腐）',
    kcal: '44',
    protein: '4',
    lipid: '2',
    carbo: '4',
  },
  {
    name: '味噌汁（しじみ）',
    kcal: '35',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（大根と油揚げ）',
    kcal: '51',
    protein: '3',
    lipid: '3',
    carbo: '4',
  },
  {
    name: '味噌汁（あさりとネギ）',
    kcal: '34',
    protein: '3',
    lipid: '1',
    carbo: '3',
  },
  {
    name: '味噌汁（あさりとわかめ）',
    kcal: '34',
    protein: '4',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（小松菜と油揚げ）',
    kcal: '52',
    protein: '4',
    lipid: '3',
    carbo: '4',
  },
  {
    name: '味噌汁（玉ねぎとじゃがいも）',
    kcal: '86',
    protein: '4',
    lipid: '1',
    carbo: '17',
  },
  {
    name: '味噌汁（小松菜と千切り大根）',
    kcal: '37',
    protein: '3',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（根菜）',
    kcal: '63',
    protein: '3',
    lipid: '1',
    carbo: '12',
  },
  {
    name: '味噌汁（さつまいも）',
    kcal: '62',
    protein: '2',
    lipid: '1',
    carbo: '11',
  },
  {
    name: '味噌汁（里芋と大豆）',
    kcal: '80',
    protein: '5',
    lipid: '2',
    carbo: '11',
  },
  {
    name: '味噌汁（豆腐）',
    kcal: '47',
    protein: '4',
    lipid: '2',
    carbo: '4',
  },
  {
    name: '味噌汁（豆腐とまいたけ）',
    kcal: '69',
    protein: '6',
    lipid: '3',
    carbo: '6',
  },
  {
    name: '味噌汁（ほうれん草とえのき）',
    kcal: '33',
    protein: '3',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（モロヘイヤとみょうが）',
    kcal: '41',
    protein: '3',
    lipid: '1',
    carbo: '6',
  },
  {
    name: '味噌汁（わかめとしめじ）',
    kcal: '29',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（玉ねぎ）',
    kcal: '33',
    protein: '2',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（豆腐とネギ）',
    kcal: '47',
    protein: '4',
    lipid: '2',
    carbo: '5',
  },
  {
    name: '味噌汁（長ねぎ）',
    kcal: '30',
    protein: '2',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（なす）',
    kcal: '32',
    protein: '2',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（なす）',
    kcal: '32',
    protein: '2',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（なめこ）',
    kcal: '29',
    protein: '2',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（白菜と油揚げ）',
    kcal: '53',
    protein: '4',
    lipid: '3',
    carbo: '5',
  },
  {
    name: '味噌汁（ほうれん草と麩）',
    kcal: '35',
    protein: '3',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（もやし）',
    kcal: '30',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: 'コンソメスープ',
    kcal: '15',
    protein: '0',
    lipid: '0',
    carbo: '3',
  },
  {
    name: 'たまごスープ',
    kcal: '45',
    protein: '3',
    lipid: '2',
    carbo: '4',
  },
  {
    name: 'わかめスープ',
    kcal: '14',
    protein: '2',
    lipid: '1',
    carbo: '1',
  },
  {
    name: '野菜スープ',
    kcal: '14',
    protein: '1',
    lipid: '0',
    carbo: '3',
  },
  {
    name: '具だくさん野菜スープ',
    kcal: '100',
    protein: '2',
    lipid: '6',
    carbo: '11',
  },
  {
    name: 'かぼちゃのポタージュ',
    kcal: '147',
    protein: '5',
    lipid: '4',
    carbo: '23',
  },
  {
    name: 'ミネストローネ',
    kcal: '104',
    protein: '3',
    lipid: '4',
    carbo: '14',
  },
  {
    name: 'ふかひれスープ',
    kcal: '56',
    protein: '8',
    lipid: '2',
    carbo: '2',
  },
  {
    name: 'デトックススープ',
    kcal: '72',
    protein: '3',
    lipid: '1',
    carbo: '16',
  },
  {
    name: 'サンラータン',
    kcal: '71',
    protein: '8',
    lipid: '3',
    carbo: '3',
  },
  {
    name: 'コーンポタージュ',
    kcal: '145',
    protein: '6',
    lipid: '6',
    carbo: '17',
  },
  {
    name: 'サムゲタン（参鶏湯）',
    kcal: '247',
    protein: '22',
    lipid: '10',
    carbo: '15',
  },
  {
    name: 'トムヤムクン',
    kcal: '156',
    protein: '15',
    lipid: '6',
    carbo: '7',
  },
  {
    name: '春雨スープ',
    kcal: '67',
    protein: '4',
    lipid: '2',
    carbo: '7',
  },
  {
    name: 'スープ餃子',
    kcal: '158',
    protein: '6',
    lipid: '8',
    carbo: '17',
  },
  {
    name: 'トースト（4枚切り）',
    kcal: '264',
    protein: '9',
    lipid: '4',
    carbo: '47',
  },
  {
    name: 'トースト（5枚切り）',
    kcal: '185',
    protein: '7',
    lipid: '3',
    carbo: '33',
  },
  {
    name: 'トースト（6枚切り）',
    kcal: '158',
    protein: '6',
    lipid: '3',
    carbo: '28',
  },
  {
    name: 'トースト（8枚切り）',
    kcal: '132',
    protein: '5',
    lipid: '2',
    carbo: '23',
  },
  {
    name: '納豆トースト',
    kcal: '400',
    protein: '19',
    lipid: '20',
    carbo: '35',
  },
  {
    name: 'ガーリックトースト',
    kcal: '102',
    protein: '3',
    lipid: '2',
    carbo: '18',
  },
  {
    name: 'ハニートースト',
    kcal: '407',
    protein: '10',
    lipid: '15',
    carbo: '58',
  },
  {
    name: 'ハムチーズトースト',
    kcal: '322',
    protein: '13',
    lipid: '17',
    carbo: '29',
  },
  {
    name: 'シュガートースト',
    kcal: '233',
    protein: '6',
    lipid: '9',
    carbo: '32',
  },
  {
    name: 'ハムトースト',
    kcal: '257',
    protein: '9',
    lipid: '12',
    carbo: '28',
  },
  {
    name: 'フレンチトースト',
    kcal: '393',
    protein: '12',
    lipid: '19',
    carbo: '42',
  },
  {
    name: 'チーズトースト',
    kcal: '223',
    protein: '10',
    lipid: '8',
    carbo: '28',
  },
  {
    name: 'ピザトースト',
    kcal: '391',
    protein: '17',
    lipid: '14',
    carbo: '49',
  },
  {
    name: 'フランスパン',
    kcal: '84',
    protein: '3',
    lipid: '0',
    carbo: '17',
  },
  {
    name: 'クロワッサン',
    kcal: '224',
    protein: '4',
    lipid: '13',
    carbo: '22',
  },
  {
    name: 'ハムチーズクロワッサン',
    kcal: '155',
    protein: '6',
    lipid: '6',
    carbo: '18',
  },
  {
    name: 'ベーコンエッグクロワッサン',
    kcal: '192',
    protein: '5',
    lipid: '11',
    carbo: '18',
  },
  {
    name: 'チョコクロワッサン',
    kcal: '308',
    protein: '5',
    lipid: '19',
    carbo: '30',
  },
  {
    name: 'チョコパン',
    kcal: '203',
    protein: '5',
    carbo: '29',
  },
  {
    name: 'イングリッシュマフィン',
    kcal: '109',
    protein: '4',
    lipid: '1',
    carbo: '21',
  },
  {
    name: 'おからパン',
    kcal: '314',
    protein: '10',
    lipid: '7',
    lipid: '3',
    carbo: '61',
  },
  {
    name: 'フォカッチャ',
    kcal: '213',
    protein: '6',
    lipid: '3',
    carbo: '37',
  },
  {
    name: 'くるみパン',
    kcal: '151',
    protein: '4',
    lipid: '6',
    carbo: '20',
  },
  {
    name: 'ミルクパン',
    kcal: '69',
    protein: '2',
    lipid: '2',
    carbo: '11',
  },
  {
    name: 'ライ麦パン（4枚切り）',
    kcal: '264',
    protein: '8',
    lipid: '2',
    carbo: '53',
  },
  {
    name: 'ライ麦パン（6枚切り）',
    kcal: '158',
    protein: '5',
    lipid: '1',
    carbo: '32',
  },
  {
    name: 'ライ麦パン（8枚切り）',
    kcal: '132',
    protein: '4',
    lipid: '1',
    carbo: '26',
  },
  {
    name: 'ロールパン',
    kcal: '316',
    protein: '10',
    lipid: '9',
    carbo: '49',
  },
  {
    name: 'シナモンロール',
    kcal: '303',
    protein: '5',
    lipid: '10',
    carbo: '50',
  },
  {
    name: 'バターロール',
    kcal: '95',
    protein: '3',
    lipid: '3',
    carbo: '15',
  },
  {
    name: 'バターロール（マーガリン入り）',
    kcal: '141',
    protein: '3',
    lipid: '8',
    carbo: '15',
  },
  {
    name: 'レーズンロール',
    kcal: '141',
    protein: '4',
    lipid: '2',
    carbo: '26',
  },
  {
    name: '黒糖ロール',
    kcal: '170',
    protein: '5',
    lipid: '4',
    carbo: '28',
  },
  {
    name: '黒糖ロール（マーガリン入り）',
    kcal: '247',
    protein: '5',
    lipid: '12',
    carbo: '28',
  },
  {
    name: '明太ポテトチーズパン',
    kcal: '242',
    protein: '7',
    lipid: '9',
    carbo: '32',
  },
  {
    name: '塩バターパン',
    kcal: '188',
    protein: '4',
    lipid: '9',
    carbo: '21',
  },
  {
    name: 'コーンパン',
    kcal: '195',
    protein: '6',
    lipid: '4',
    carbo: '32',
  },
  {
    name: 'クイニーアマン',
    kcal: '389',
    protein: '4',
    lipid: '17',
    carbo: '54',
  },
  {
    name: 'ベーグル',
    kcal: '166',
    protein: '5',
    lipid: '1',
    carbo: '34',
  },
  {
    name: 'ブルーベリーベーグル',
    kcal: '212',
    protein: '6',
    lipid: '1',
    carbo: '43',
  },
  {
    name: 'オニオンベーグル',
    kcal: '216',
    protein: '6',
    lipid: '2',
    carbo: '40',
  },
  {
    name: 'シナモンベーグル',
    kcal: '197',
    protein: '6',
    lipid: '1',
    carbo: '39',
  },
  {
    name: 'ぶどうパン（4枚切り）',
    kcal: '269',
    protein: '8',
    lipid: '4',
    carbo: '51',
  },
  {
    name: 'ぶどうパン（6枚切り）',
    kcal: '161',
    protein: '5',
    lipid: '2',
    carbo: '31',
  },
  {
    name: 'ぶどうパン（8枚切り）',
    kcal: '135',
    protein: '4',
    lipid: '2',
    carbo: '26',
  },
  {
    name: '玄米パン',
    kcal: '149',
    protein: '5',
    lipid: '2',
    carbo: '27',
  },
  {
    name: 'オリーブパン',
    kcal: '152',
    protein: '4',
    lipid: '3',
    carbo: '26',
  },
  {
    name: 'ソーセージパン',
    kcal: '262',
    protein: '7',
    lipid: '13',
    carbo: '28',
  },
  {
    name: 'イチジクパン',
    kcal: '141',
    protein: '4',
    lipid: '3',
    carbo: '26',
  },
  {
    name: 'カンパーニュ',
    kcal: '1146',
    protein: '37',
    lipid: '6',
    carbo: '228',
  },
  {
    name: 'クランベリーパン',
    kcal: '125',
    protein: '3',
    lipid: '2',
    carbo: '24',
  },
  {
    name: 'ミックスサンド',
    kcal: '382',
    protein: '12',
    lipid: '27',
    carbo: '22',
  },
  {
    name: 'たまごサンド',
    kcal: '285',
    protein: '9',
    lipid: '19',
    carbo: '20',
  },
  {
    name: 'ハムと野菜サンド',
    kcal: '248',
    protein: '6',
    lipid: '16',
    carbo: '20',
  },
  {
    name: 'カツサンド',
    kcal: '346',
    protein: '15',
    lipid: '20',
    carbo: '27',
  },
  {
    name: 'ハムたまごサンド',
    kcal: '246',
    protein: '8',
    lipid: '15',
    carbo: '20',
  },
  {
    name: 'ハムチーズサンド',
    kcal: '228',
    protein: '10',
    lipid: '12',
    carbo: '20',
  },
  {
    name: '照焼きチキンとたまごのサンド',
    kcal: '373',
    protein: '19',
    lipid: '18',
    carbo: '30',
  },
  {
    name: 'ハムカツサンド',
    kcal: '300',
    protein: '12',
    lipid: '16',
    carbo: '26',
  },
  {
    name: 'ハムカツたまごサンド',
    kcal: '390',
    protein: '11',
    lipid: '20',
    carbo: '39',
  },
  {
    name: 'バケットサンドイッチ（ハムとレタスとチーズ）',
    kcal: '405',
    protein: '21',
    lipid: '14',
    carbo: '47',
  },
  {
    name: 'ハムサンド',
    kcal: '208',
    protein: '9',
    lipid: '10',
    carbo: '20',
  },
  {
    name: 'ハムチーズエッグレタスサンド',
    kcal: '268',
    protein: '13',
    lipid: '15',
    carbo: '20',
  },
  {
    name: 'ハムマヨネーズサンド',
    kcal: '305',
    protein: '9',
    lipid: '21',
    carbo: '20',
  },
  {
    name: 'BLTサンド',
    kcal: '229',
    protein: '6',
    lipid: '14',
    carbo: '21',
  },
  {
    name: 'フルーツサンド',
    kcal: '398',
    protein: '8',
    lipid: '24',
    carbo: '37',
  },
  {
    name: 'ホットサンド（ハムチーズ）',
    kcal: '283',
    protein: '12',
    lipid: '17',
    carbo: '20',
  },
  {
    name: '野菜サンド',
    kcal: '181',
    protein: '4',
    lipid: '9',
    carbo: '21',
  },
  {
    name: 'メンチカツたまごサンド',
    kcal: '436',
    protein: '12',
    lipid: '28',
    carbo: '34',
  },
  {
    name: 'レタスサンド',
    kcal: '257',
    protein: '12',
    lipid: '14',
    carbo: '21',
  },
  {
    name: 'ゆでたまごのBLTサンド',
    kcal: '357',
    protein: '12',
    lipid: '20',
    carbo: '32',
  },
  {
    name: 'ツナサンド',
    kcal: '308',
    protein: '10',
    lipid: '21',
    carbo: '20',
  },
  {
    name: 'ツナたまごサンド',
    kcal: '300',
    protein: '9',
    lipid: '20',
    carbo: '20',
  },
  {
    name: 'チキンフィレサンド',
    kcal: '421',
    protein: '16',
    lipid: '24',
    carbo: '33',
  },
  {
    name: 'チキンサンド',
    kcal: '332',
    protein: '15',
    lipid: '17',
    carbo: '29',
  },
  {
    name: 'チキンカツサンド',
    kcal: '394',
    protein: '15',
    lipid: '22',
    carbo: '31',
  },
  {
    name: 'たまご焼きサンド',
    kcal: '308',
    protein: '17',
    lipid: '17',
    carbo: '20',
  },
  {
    name: 'ジャムサンド',
    kcal: '157',
    protein: '4',
    lipid: '2',
    carbo: '31',
  },
  {
    name: 'コロッケサンド',
    kcal: '331',
    protein: '8',
    lipid: '18',
    carbo: '34',
  },
  {
    name: 'クラブハウスサンド',
    kcal: '480',
    protein: '18',
    lipid: '31',
    carbo: '31',
  },
  {
    name: 'エビカツサンド',
    kcal: '265',
    protein: '11',
    lipid: '9',
    carbo: '34',
  },
  {
    name: 'アボカドバーガー',
    kcal: '429',
    protein: '12',
    lipid: '28',
    carbo: '34',
  },
  {
    name: 'エッグバーガー',
    kcal: '339',
    protein: '15',
    lipid: '14',
    carbo: '38',
  },
  {
    name: 'エビバーガー',
    kcal: '444',
    protein: '15',
    lipid: '22',
    carbo: '46',
  },
  {
    name: 'ダブルチーズバーガー',
    kcal: '532',
    protein: '26',
    lipid: '27',
    carbo: '47',
  },
  {
    name: 'チーズバーガー',
    kcal: '385',
    protein: '15',
    lipid: '18',
    carbo: '40',
  },
  {
    name: 'チキンカツマフィンバーガー',
    kcal: '329',
    protein: '13',
    lipid: '18',
    carbo: '26',
  },
  {
    name: 'チキン竜田和風おろしバーガー',
    kcal: '427',
    protein: '26',
    lipid: '14',
    carbo: '41',
  },
  {
    name: '照焼きたまごバーガー',
    kcal: '392',
    protein: '17',
    lipid: '16',
    carbo: '44',
  },
  {
    name: 'テリヤキバーガー',
    kcal: '451',
    protein: '19',
    lipid: '26',
    carbo: '34',
  },
  {
    name: 'ハンバーガー',
    kcal: '319',
    protein: '12',
    lipid: '12',
    carbo: '41',
  },
  {
    name: 'ビッグハンバーガー',
    kcal: '575',
    protein: '27',
    lipid: '26',
    carbo: '57',
  },
  {
    name: 'フィッシュバーガー',
    kcal: '376',
    protein: '12',
    lipid: '18',
    carbo: '42',
  },
  {
    name: 'ベーコンエッグバーガー',
    kcal: '390',
    protein: '17',
    lipid: '18',
    carbo: '39',
  },
  {
    name: 'ベーコンレタスバーガー',
    kcal: '327',
    protein: '12',
    lipid: '14',
    carbo: '39',
  },
  {
    name: 'ベーコンバーガー',
    kcal: '323',
    protein: '12',
    lipid: '14',
    carbo: '38',
  },
  {
    name: 'カレーパン',
    kcal: '351',
    protein: '11',
    lipid: '12',
    carbo: '49',
  },
  {
    name: 'ホットドッグ',
    kcal: '291',
    protein: '10',
    lipid: '15',
    carbo: '29',
  },
  {
    name: 'コロッケパン',
    kcal: '315',
    protein: '7',
    lipid: '13',
    carbo: '42',
  },
  {
    name: 'エッグベネディクト',
    kcal: '710',
    protein: '27',
    lipid: '52',
    carbo: '30',
  },
  {
    name: 'お好み焼きパン',
    kcal: '269',
    protein: '13',
    lipid: '14',
    carbo: '45',
  },
  {
    name: 'カルツォーネ',
    kcal: '443',
    protein: '16',
    lipid: '14',
    carbo: '62',
  },
  {
    name: 'グラタンパン',
    kcal: '340',
    protein: '14',
    lipid: '10',
    carbo: '49',
  },
  {
    name: 'ケークサレ',
    kcal: '136',
    protein: '6',
    lipid: '9',
    carbo: '10',
  },
  {
    name: '焼きそばパン',
    kcal: '258',
    protein: '8',
    lipid: '7',
    carbo: '41',
  },
  {
    name: '焼きカレーパン',
    kcal: '304',
    protein: '11',
    lipid: '7',
    carbo: '49',
  },
  {
    name: 'ムルタバ',
    kcal: '508',
    protein: '15',
    lipid: '26',
    carbo: '51',
  },
  {
    name: 'ミートパイ',
    kcal: '397',
    protein: '10',
    lipid: '30',
    carbo: '22',
  },
  {
    name: 'ポンデケージョ',
    kcal: '74',
    protein: '2',
    lipid: '4',
    carbo: '8',
  },
  {
    name: 'ブルスケッタ',
    kcal: '152',
    protein: '4',
    lipid: '3',
    carbo: '27',
  },
  {
    name: 'クリームパン',
    kcal: '275',
    protein: '9',
    lipid: '10',
    carbo: '37',
  },
  {
    name: 'あんぱん',
    kcal: '252',
    protein: '7',
    lipid: '5',
    carbo: '45',
  },
  {
    name: 'メロンパン',
    kcal: '366',
    protein: '8',
    lipid: '11',
    carbo: '60',
  },
  {
    name: 'パンケーキ',
    kcal: '117',
    protein: '3',
    lipid: '4',
    carbo: '17',
  },
  {
    name: 'スコーン',
    kcal: '137',
    protein: '2',
    lipid: '6',
    carbo: '18',
  },
  {
    name: 'アーモンドナッツバナナマフィン',
    kcal: '249',
    protein: '4',
    lipid: '15',
    carbo: '25',
  },
  {
    name: 'アップルクリームデニッシュ',
    kcal: '330',
    protein: '5',
    lipid: '21',
    carbo: '29',
  },
  {
    name: 'アップルデニッシュ',
    kcal: '312',
    protein: '5',
    lipid: '20',
    carbo: '26',
  },
  {
    name: 'あんこサンド（ホイップ入り）',
    kcal: '312',
    protein: '8',
    lipid: '10',
    carbo: '47',
  },
  {
    name: 'アンドーナツ',
    kcal: '321',
    protein: '7',
    lipid: '12',
    carbo: '45',
  },
  {
    name: 'おからパンケーキ',
    kcal: '131',
    protein: '4',
    lipid: '4',
    carbo: '20',
  },
  {
    name: 'おから蒸しパン',
    kcal: '60',
    protein: '3',
    lipid: '3',
    carbo: '6',
  },
  {
    name: 'オレンジブレッド',
    kcal: '161',
    protein: '4',
    lipid: '1',
    carbo: '33',
  },
  {
    name: 'かぼちゃデニッシュ',
    kcal: '278',
    protein: '4',
    lipid: '20',
    carbo: '21',
  },
  {
    name: 'かぼちゃパン',
    kcal: '229',
    protein: '4',
    lipid: '9',
    carbo: '32',
  },
  {
    name: 'かぼちゃマフィン',
    kcal: '222',
    protein: '3',
    lipid: '10',
    carbo: '30',
  },
  {
    name: 'きなこ揚げパン',
    kcal: '387',
    protein: '12',
    lipid: '12',
    carbo: '59',
  },
  {
    name: '紅茶パン',
    kcal: '366',
    protein: '8',
    lipid: '11',
    carbo: '60',
  },
  {
    name: 'コッペパン',
    kcal: '265',
    protein: '9',
    lipid: '4',
    carbo: '49',
  },
  {
    name: '米粉パンケーキ',
    kcal: '150',
    protein: '3',
    lipid: '4',
    carbo: '25',
  },
  {
    name: 'さつまいもパン',
    kcal: '313',
    protein: '7',
    lipid: '5',
    carbo: '60',
  },
  {
    name: 'ジャムパン',
    kcal: '327',
    protein: '7',
    lipid: '6',
    carbo: '60',
  },
  {
    name: 'シュトーレン',
    kcal: '282',
    protein: '4',
    lipid: '19',
    carbo: '21',
  },
  {
    name: 'ショコラパン',
    kcal: '165',
    protein: '5',
    lipid: '6',
    carbo: '25',
  },
  {
    name: 'チョココロネ',
    kcal: '371',
    protein: '8',
    lipid: '17',
    carbo: '47',
  },
  {
    name: 'チョコスコーン',
    kcal: '170',
    protein: '3',
    lipid: '8',
    carbo: '21',
  },
  {
    name: 'チョコスティックパン',
    kcal: '189',
    protein: '5',
    lipid: '5',
    carbo: '30',
  },
  {
    name: 'チョコチップマフィン',
    kcal: '274',
    protein: '4',
    lipid: '15',
    carbo: '32',
  },
  {
    name: 'バタースコッチ',
    kcal: '613',
    protein: '11',
    lipid: '33',
    carbo: '65',
  },
  {
    name: 'バナナマフィン',
    kcal: '216',
    protein: '3',
    lipid: '10',
    carbo: '28',
  },
  {
    name: 'ブルーベリースコーン',
    kcal: '140',
    protein: '2',
    lipid: '6',
    carbo: '19',
  },
  {
    name: 'ブルーベリーマフィン',
    kcal: '215',
    protein: '3',
    lipid: '10',
    carbo: '28',
  },
  {
    name: 'ホイップクロワッサン',
    kcal: '435',
    protein: '6',
    lipid: '31',
    carbo: '31',
  },
  {
    name: 'マフィン',
    kcal: '167',
    protein: '2',
    lipid: '9',
    carbo: '18',
  },
  {
    name: 'ミルクフランス',
    kcal: '261',
    protein: '5',
    lipid: '9',
    carbo: '37',
  },
  {
    name: '蒸しパン（黒糖）',
    kcal: '209',
    protein: '5',
    lipid: '3',
    carbo: '39',
  },
  {
    name: '蒸しパン（プレーン）',
    kcal: '211',
    protein: '5',
    lipid: '3',
    carbo: '40',
  },
  {
    name: '蒸しパン（チーズ）',
    kcal: '306',
    protein: '14',
    lipid: '9',
    carbo: '40',
  },
  {
    name: 'メープルパン',
    kcal: '375',
    protein: '6',
    lipid: '17',
    carbo: '47',
  },
  {
    name: 'メイプルスコーン',
    kcal: '150',
    protein: '2',
    lipid: '6',
    carbo: '21',
  },
  {
    name: 'レーズンカスタードパン',
    kcal: '279',
    protein: '7',
    lipid: '7',
    carbo: '46',
  },
  {
    name: 'レーズンフランス',
    kcal: '281',
    protein: '8',
    lipid: '1',
    carbo: '59',
  },
  {
    name: '明太ポテトサラダコッペ',
    kcal: '343',
    protein: '10',
    lipid: '13',
    carbo: '48',
  },
  {
    name: 'オートミール',
    kcal: '152',
    protein: '6',
    lipid: '2',
    carbo: '28',
  },
  {
    name: 'コーンフレーク',
    kcal: '152',
    protein: '3',
    lipid: '1',
    carbo: '33',
  },
  {
    name: '玄米フレーク',
    kcal: '150',
    protein: '3',
    lipid: '1',
    carbo: '33',
  },
  {
    name: 'ハニーナッツクランチ',
    kcal: '158',
    protein: '3',
    lipid: '2',
    carbo: '34',
  },
  {
    name: 'ドライフルーツ入りシリアル（グラノーラ）',
    kcal: '200',
    protein: '6',
    lipid: '2',
    carbo: '36',
  },
  {
    name: 'チョココーンフレーク',
    kcal: '208',
    protein: '4',
    lipid: '4',
    carbo: '39',
  },
  {
    name: 'フルーツグラノーラ（チョコレート入り）',
    kcal: '278',
    protein: '4',
    lipid: '9',
    carbo: '44',
  },
  {
    name: 'アーモンドブリオッシュ',
    kcal: '306',
    protein: '9',
    lipid: '7',
    carbo: '50',
  },
  {
    name: 'アイスのせフォカッチャ',
    kcal: '285',
    protein: '8',
    lipid: '7',
    carbo: '47',
  },
  {
    name: '肉まん',
    kcal: '202',
    protein: '7',
    lipid: '7',
    carbo: '27',
  },
  {
    name: 'あんまん',
    kcal: '227',
    protein: '5',
    lipid: '5',
    carbo: '41',
  },
  {
    name: 'ピザまん',
    kcal: '200',
    protein: '7',
    lipid: '6',
    carbo: '28',
  },
  {
    name: '中華まん',
    kcal: '256',
    protein: '9',
    lipid: '7',
    carbo: '36',
  },
  {
    name: 'もんじゃ焼き',
    kcal: '273',
    protein: '6',
    lipid: '16',
    carbo: '25',
  },
  {
    name: 'モダン焼き',
    kcal: '859',
    protein: '26',
    lipid: '38',
    carbo: '98',
  },
  {
    name: '広島風お好み焼き',
    kcal: '652',
    protein: '23',
    lipid: '23',
    carbo: '82',
  },
  {
    name: 'お好み焼き',
    kcal: '545',
    protein: '19',
    lipid: '30',
    carbo: '46',
  },
  {
    name: 'たこ焼き（6個）',
    kcal: '169',
    protein: '12',
    lipid: '3',
    carbo: '23',
  },
  {
    name: 'タコス',
    kcal: '324',
    protein: '9',
    lipid: '17',
    carbo: '11',
  },
  {
    name: 'トルティーヤ（鶏肉と野菜）',
    kcal: '122',
    protein: '7',
    lipid: '5',
    carbo: '12',
  },
  {
    name: 'トルティーヤ（牛肉と野菜）',
    kcal: '115',
    protein: '5',
    lipid: '5',
    carbo: '11',
  },
  {
    name: 'チャパティ',
    kcal: '96',
    protein: '3',
    lipid: '2',
    carbo: '17',
  },
  {
    name: 'チヂミ',
    kcal: '558',
    protein: '25',
    lipid: '11',
    carbo: '85',
  },
  {
    name: 'ナン',
    kcal: '393',
    protein: '16',
    lipid: '5',
    carbo: '71',
  },
  {
    name: 'かけうどん',
    kcal: '311',
    protein: '9',
    lipid: '1',
    carbo: '62',
  },
  {
    name: 'カレーうどん',
    kcal: '429',
    protein: '14',
    lipid: '9',
    carbo: '68',
  },
  {
    name: 'きつねうどん',
    kcal: '470',
    protein: '18',
    lipid: '11',
    carbo: '68',
  },
  {
    name: '肉うどん',
    kcal: '464',
    protein: '23',
    lipid: '10',
    carbo: '64',
  },
  {
    name: 'ざるうどん',
    kcal: '341',
    protein: '10',
    lipid: '2',
    carbo: '67',
  },
  {
    name: '伊勢うどん',
    kcal: '365',
    protein: '12',
    lipid: '1',
    carbo: '69',
  },
  {
    name: '月見うどん',
    kcal: '395',
    protein: '17',
    lipid: '6',
    carbo: '65',
  },
  {
    name: '天ぷらうどん',
    kcal: '473',
    protein: '23',
    lipid: '8',
    carbo: '71',
  },
  {
    name: 'かき玉うどん',
    kcal: '414',
    protein: '20',
    lipid: '4',
    carbo: '71',
  },
  {
    name: 'かきあげうどん',
    kcal: '691',
    protein: '13',
    lipid: '26',
    carbo: '97',
  },
  {
    name: '鍋焼きうどん',
    kcal: '502',
    protein: '25',
    lipid: '12',
    carbo: '69',
  },
  {
    name: 'ごぼう天うどん',
    kcal: '507',
    protein: '15',
    lipid: '3',
    carbo: '100',
  },
  {
    name: 'わかめうどん',
    kcal: '315',
    protein: '10',
    lipid: '1',
    carbo: '63',
  },
  {
    name: 'とろろうどん',
    kcal: '355',
    protein: '11',
    lipid: '1',
    carbo: '71',
  },
  {
    name: '味噌煮込みうどん',
    kcal: '428',
    protein: '18',
    lipid: '4',
    carbo: '77',
  },
  {
    name: 'ざるそば',
    kcal: '332',
    protein: '13',
    lipid: '2',
    carbo: '2',
  },
  {
    name: '天ぷらそば',
    kcal: '431',
    protein: '23',
    lipid: '7',
    carbo: '66',
  },
  {
    name: '山菜そば',
    kcal: '332',
    protein: '15',
    lipid: '2',
    carbo: '63',
  },
  {
    name: 'かけそば',
    kcal: '313',
    protein: '12',
    lipid: '2',
    carbo: '60',
  },
  {
    name: 'かきあげそば',
    kcal: '692',
    protein: '16',
    lipid: '27',
    carbo: '95',
  },
  {
    name: 'えび天そば',
    kcal: '427',
    protein: '21',
    lipid: '7',
    carbo: '69',
  },
  {
    name: '月見そば',
    kcal: '397',
    protein: '20',
    lipid: '7',
    carbo: '63',
  },
  {
    name: 'にしんそば',
    kcal: '483',
    protein: '24',
    lipid: '11',
    carbo: '68',
  },
  {
    name: 'ごぼう天そば',
    kcal: '776',
    protein: '27',
    lipid: '5',
    carbo: '151',
  },
  {
    name: 'おろしそば',
    kcal: '341',
    protein: '14',
    lipid: '2',
    carbo: '64',
  },
  {
    name: '瓦そば',
    kcal: '715',
    protein: '28',
    lipid: '25',
    carbo: '86',
  },
  {
    name: '五目あんかけそば',
    kcal: '456',
    protein: '25',
    lipid: '8',
    carbo: '69',
  },
  {
    name: '昆布そば',
    kcal: '366',
    protein: '15',
    lipid: '4',
    carbo: '67',
  },
  {
    name: '鴨そば',
    kcal: '604',
    protein: '26',
    lipid: '26',
    carbo: '63',
  },
  {
    name: '鴨南蛮そば',
    kcal: '428',
    protein: '17',
    lipid: '11',
    carbo: '64',
  },
  {
    name: 'そうめん',
    kcal: '378',
    protein: '11',
    lipid: '1',
    carbo: '77',
  },
  {
    name: 'にゅうめん',
    kcal: '360',
    protein: '17',
    lipid: '1',
    carbo: '65',
  },
  {
    name: 'ひやむぎ',
    kcal: '445',
    protein: '14',
    lipid: '5',
    carbo: '81',
  },
  {
    name: '刀削麺',
    kcal: '668',
    protein: '27',
    lipid: '22',
    carbo: '84',
  },
  {
    name: 'すき焼きうどん',
    kcal: '582',
    protein: '19',
    lipid: '18',
    carbo: '78',
  },
  {
    name: '鴨南蛮うどん',
    kcal: '427',
    protein: '14',
    lipid: '10',
    carbo: '66',
  },
  {
    name: 'うどん定食',
    kcal: '679',
    protein: '22',
    lipid: '5',
    carbo: '128',
  },
  {
    name: 'そば定食',
    kcal: '613',
    protein: '16',
    lipid: '3',
    carbo: '126',
  },
  {
    name: 'しょうゆラーメン',
    kcal: '502',
    protein: '22',
    lipid: '8',
    carbo: '80',
  },
  {
    name: 'とんこつラーメン',
    kcal: '479',
    protein: '21',
    lipid: '8',
    carbo: '77',
  },
  {
    name: 'みそラーメン',
    kcal: '519',
    protein: '22',
    lipid: '9',
    carbo: '84',
  },
  {
    name: 'しおラーメン',
    kcal: '461',
    protein: '20',
    lipid: '7',
    carbo: '76',
  },
  {
    name: '担々麺',
    kcal: '647',
    protein: '30',
    lipid: '20',
    carbo: '82',
  },
  {
    name: '油そば',
    kcal: '552',
    protein: '23',
    lipid: '13',
    carbo: '81',
  },
  {
    name: 'ちゃんぽん',
    kcal: '632',
    protein: '33',
    lipid: '19',
    carbo: '76',
  },
  {
    name: 'とんこつ醤油ラーメン',
    kcal: '497',
    protein: '22',
    lipid: '8',
    carbo: '79',
  },
  {
    name: '冷やし担々麺',
    kcal: '656',
    protein: '29',
    lipid: '21',
    carbo: '82',
  },
  {
    name: 'ワンタン麺',
    kcal: '555',
    protein: '19',
    lipid: '11',
    carbo: '90',
  },
  {
    name: 'ジャージャー麺',
    kcal: '690',
    protein: '31',
    lipid: '22',
    carbo: '86',
  },
  {
    name: '蒟蒻ラーメン（とんこつ味）',
    kcal: '101',
    protein: '2',
    lipid: '9',
    carbo: '6',
  },
  {
    name: '蒟蒻ラーメン,（みそ味）',
    kcal: '79',
    protein: '4',
    lipid: '3',
    carbo: '11',
  },
  {
    name: '焼きうどん',
    kcal: '450',
    protein: '15',
    lipid: '15',
    carbo: '60',
  },
  {
    name: 'ソース焼きそば',
    kcal: '487',
    protein: '15',
    lipid: '17',
    carbo: '67',
  },
  {
    name: '塩焼きそば',
    kcal: '494',
    protein: '14',
    lipid: '19',
    carbo: '63',
  },
  {
    name: 'チャプチェ',
    kcal: '300',
    protein: '9',
    lipid: '14',
    carbo: '35',
  },
  {
    name: '焼きビーフン',
    kcal: '485',
    protein: '16',
    lipid: '17',
    carbo: '62',
  },
  {
    name: '冷麺',
    kcal: '478',
    protein: '22',
    lipid: '8',
    carbo: '78',
  },
  {
    name: '焼きそば定食',
    kcal: '843',
    protein: '22',
    lipid: '20',
    carbo: '138',
  },
  {
    name: 'ラーメン定食',
    kcal: '839',
    protein: '31',
    lipid: '23',
    carbo: '119',
  },
  {
    name: 'ミートソーススパゲティ',
    kcal: '677',
    protein: '23',
    lipid: '23',
    carbo: '89',
  },
  {
    name: 'トマトソーススパゲティ',
    kcal: '535',
    protein: '14',
    lipid: '14',
    carbo: '82',
  },
  {
    name: '牛肉のボロネーゼスパゲティ',
    kcal: '949',
    protein: '31',
    lipid: '48',
    carbo: '87',
  },
  {
    name: 'ナポリタンスパゲティ',
    kcal: '590',
    protein: '18',
    lipid: '20',
    carbo: '80',
  },
  {
    name: 'ナスのトマトソーススパゲティ',
    kcal: '617',
    protein: '15',
    lipid: '20',
    carbo: '89',
  },
  {
    name: 'たらこスパゲティ',
    kcal: '475',
    protein: '22',
    lipid: '10',
    carbo: '71',
  },
  {
    name: 'きのこスパゲティ',
    kcal: '435',
    protein: '14',
    lipid: '8',
    carbo: '74',
  },
  {
    name: '明太子スパゲティ',
    kcal: '477',
    protein: '21',
    lipid: '9',
    carbo: '73',
  },
  {
    name: 'あさり和風パスタ',
    kcal: '525',
    protein: '17',
    lipid: '13',
    carbo: '80',
  },
  {
    name: 'きのことベーコンの和風スパゲティ',
    kcal: '631',
    protein: '21',
    lipid: '24',
    carbo: '81',
  },
  {
    name: 'きのこと野菜の和風スパゲティ',
    kcal: '507',
    protein: '16',
    lipid: '13',
    carbo: '80',
  },
  {
    name: 'カルボナーラ',
    kcal: '640',
    protein: '20',
    lipid: '28',
    carbo: '73',
  },
  {
    name: 'エビのトマトクリームスパゲティ',
    kcal: '589',
    protein: '18',
    lipid: '18',
    carbo: '83',
  },
  {
    name: 'きのこのクリームスパゲティ',
    kcal: '743',
    protein: '19',
    lipid: '32',
    carbo: '90',
  },
  {
    name: 'サーモンクリームパスタ',
    kcal: '650',
    protein: '28',
    lipid: '21',
    carbo: '81',
  },
  {
    name: 'トマトクリームスパゲティ',
    kcal: '547',
    protein: '13',
    lipid: '20',
    carbo: '75',
  },
  {
    name: 'スープスパゲティ',
    kcal: '545',
    protein: '17',
    lipid: '18',
    carbo: '75',
  },
  {
    name: 'ペペロンチーノ',
    kcal: '449',
    protein: '12',
    lipid: '10',
    carbo: '72',
  },
  {
    name: 'ボンゴレビアンコ',
    kcal: '504',
    protein: '15',
    lipid: '12',
    carbo: '76',
  },
  {
    name: 'バジリコスパゲティ',
    kcal: '482',
    protein: '13',
    lipid: '12',
    carbo: '73',
  },
  {
    name: 'ジェノベーゼ',
    kcal: '585',
    protein: '16',
    lipid: '19',
    carbo: '82',
  },
  {
    name: 'ほうれん草とベーコン',
    kcal: '543',
    protein: '16',
    lipid: '19',
    carbo: '74',
  },
  {
    name: 'ポテトグラタン',
    kcal: '378',
    protein: '14',
    lipid: '22',
    carbo: '31',
  },
  {
    name: 'ラザニア',
    kcal: '535',
    protein: '22',
    lipid: '27',
    carbo: '46',
  },
  {
    name: 'チキングラタン',
    kcal: '546',
    protein: '28',
    lipid: '27',
    carbo: '42',
  },
  {
    name: 'ドリア',
    kcal: '638',
    protein: '17',
    lipid: '29',
    carbo: '73',
  },
  {
    name: 'エビグラタン',
    kcal: '482',
    protein: '19',
    lipid: '23',
    carbo: '47',
  },
  {
    name: 'ピザ（マルゲリータ）',
    kcal: '175',
    protein: '6',
    lipid: '6',
    carbo: '23',
  },
  {
    name: 'ピザ（シーフード）',
    kcal: '208',
    protein: '10',
    lipid: '7',
    carbo: '25',
  },
  {
    name: 'ピザ（テリヤキ）',
    kcal: '273',
    protein: '10',
    lipid: '14',
    carbo: '27',
  },
  {
    name: 'ピザ（マヨじゃが）',
    kcal: '430',
    protein: '8',
    lipid: '28',
    carbo: '38',
  },
  {
    name: 'ピザ（生ハム）',
    kcal: '245',
    protein: '12',
    lipid: '11',
    carbo: '24',
  },
  {
    name: 'ピザ（トマトとバジル）',
    kcal: '220',
    protein: '7',
    lipid: '9',
    carbo: '29',
  },
  {
    name: 'ピザ（ベーコンとほうれん草）',
    kcal: '266',
    protein: '9',
    lipid: '13',
    carbo: '28',
  },
  {
    name: 'ミックスピザ',
    kcal: '341',
    protein: '13',
    lipid: '20',
    carbo: '27',
  },
  {
    name: 'キッシュ',
    kcal: '263',
    protein: '6',
    lipid: '16',
    carbo: '23',
  },
  {
    name: 'ローストビーフ',
    kcal: '75',
    protein: '8',
    lipid: '4',
    carbo: '1',
  },
  {
    name: 'サーロインステーキ',
    kcal: '503',
    protein: '26',
    lipid: '42',
    carbo: '1',
  },
  {
    name: 'すき焼き',
    kcal: '475',
    protein: '25',
    lipid: '30',
    carbo: '23',
  },
  {
    name: 'スペアリブの煮込み',
    kcal: '285',
    protein: '19',
    lipid: '18',
    carbo: '8',
  },
  {
    name: 'タコス',
    kcal: '324',
    protein: '9',
    lipid: '17',
    carbo: '11',
  },
  {
    name: '鉄板焼き',
    kcal: '438',
    protein: '14',
    lipid: '38',
    carbo: '5',
  },
  {
    name: 'どて焼き',
    kcal: '226',
    protein: '24',
    lipid: '5',
    carbo: '18',
  },
  {
    name: '肉豆腐',
    kcal: '298',
    protein: '18',
    lipid: '18',
    carbo: '14',
  },
  {
    name: 'ビーフシチュー',
    kcal: '476',
    protein: '18',
    lipid: '35',
    carbo: '14',
  },
  {
    name: 'ヒレステーキ',
    kcal: '189',
    protein: '21',
    lipid: '11',
    carbo: '1',
  },
  {
    name: 'プルコギ',
    kcal: '300',
    protein: '22',
    lipid: '18',
    carbo: '11',
  },
  {
    name: 'ボルシチ',
    kcal: '444',
    protein: '15',
    lipid: '29',
    carbo: '30',
  },
  {
    name: 'ユッケ',
    kcal: '257',
    protein: '21',
    lipid: '15',
    carbo: '7',
  },
  {
    name: 'レバ刺し',
    kcal: '203',
    protein: '7',
    lipid: '19',
    carbo: '1',
  },
  {
    name: 'サイコロステーキ',
    kcal: '527',
    protein: '12',
    lipid: '51',
    carbo: '1',
  },
  {
    name: '焼肉',
    kcal: '223',
    protein: '9',
    lipid: '20',
    carbo: '1',
  },
  {
    name: '牛カツ',
    kcal: '397',
    protein: '24',
    lipid: '26',
    carbo: '13',
  },
  {
    name: '牛すじ煮込み',
    kcal: '206',
    protein: '26',
    lipid: '5',
    carbo: '15',
  },
  {
    name: '肉野菜炒め（豚肉）',
    kcal: '227',
    protein: '7',
    lipid: '18',
    carbo: '9',
  },
  {
    name: '肉野菜炒め（牛肉）',
    kcal: '266',
    protein: '16',
    lipid: '18',
    carbo: '6',
  },
  {
    name: '肉野菜炒め（鶏肉）',
    kcal: '178',
    protein: '13',
    lipid: '10',
    carbo: '8',
  },
  {
    name: '焼肉定食',
    kcal: '588',
    protein: '24',
    lipid: '19',
    carbo: '75',
  },
  {
    name: '豚肉の生姜焼き',
    kcal: '321',
    protein: '18',
    lipid: '22',
    carbo: '6',
  },
  {
    name: '肉じゃが',
    kcal: '293',
    protein: '11',
    lipid: '7',
    carbo: '42',
  },
  {
    name: 'とんかつ（ロースカツ）',
    kcal: '450',
    protein: '22',
    lipid: '36',
    carbo: '10',
  },
  {
    name: 'とんかつ（ヒレカツ）',
    kcal: '277',
    protein: '19',
    lipid: '17',
    carbo: '9',
  },
  {
    name: '焼きぶた',
    kcal: '160',
    protein: '11',
    lipid: '12',
    carbo: '1',
  },
  {
    name: '豚肉の角煮',
    kcal: '483',
    protein: '17',
    lipid: '38',
    carbo: '13',
  },
  {
    name: 'ゴーヤチャンプル',
    kcal: '193',
    protein: '10',
    lipid: '15',
    carbo: '4',
  },
  {
    name: 'サムギョプサル',
    kcal: '1062',
    protein: '40',
    lipid: '89',
    carbo: '15',
  },
  {
    name: '豚しゃぶ',
    kcal: '228',
    protein: '21',
    lipid: '14',
    carbo: '3',
  },
  {
    name: '酢豚',
    kcal: '568',
    protein: '16',
    lipid: '42',
    carbo: '28',
  },
  {
    name: 'どて煮',
    kcal: '370',
    protein: '22',
    lipid: '16',
    carbo: '30',
  },
  {
    name: '味噌カツ',
    kcal: '442',
    protein: '20',
    lipid: '30',
    carbo: '20',
  },
  {
    name: 'ホイコーロー',
    kcal: '453',
    protein: '11',
    lipid: '36',
    carbo: '16',
  },
  {
    name: 'ポーククリームシチュー',
    kcal: '292',
    protein: '16',
    lipid: '14',
    carbo: '22',
  },
  {
    name: 'ポークソテー',
    kcal: '308',
    protein: '20',
    lipid: '23',
    carbo: '2',
  },
  {
    name: 'ポークチャップ',
    kcal: '331',
    protein: '20',
    lipid: '19',
    carbo: '13',
  },
  {
    name: 'ポークピカタ',
    kcal: '302',
    protein: '21',
    lipid: '22',
    carbo: '3',
  },
  {
    name: '豚キムチ炒め',
    kcal: '296',
    protein: '11',
    lipid: '23',
    carbo: '9',
  },
  {
    name: 'とんかつ定食',
    kcal: '785',
    protein: '28',
    lipid: '34',
    carbo: '87',
  },
  {
    name: '鶏の唐揚げ',
    kcal: '217',
    protein: '15',
    lipid: '14',
    carbo: '5',
  },
  {
    name: 'チキンクリームシチュー',
    kcal: '352',
    protein: '14',
    lipid: '22',
    carbo: '22',
  },
  {
    name: 'チキンソテー',
    kcal: '200',
    protein: '13',
    lipid: '15',
    carbo: '0',
  },
  {
    name: '蒸しささみ',
    kcal: '38',
    protein: '8',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '蒸し鶏',
    kcal: '116',
    protein: '23',
    lipid: '2',
    carbo: '0',
  },
  {
    name: '唐揚げ定食',
    kcal: '647',
    protein: '24',
    lipid: '20',
    carbo: '89',
  },
  {
    name: '唐揚げ丼',
    kcal: '617',
    protein: '24',
    lipid: '15',
    carbo: '89',
  },
  {
    name: 'ガリバタチキン',
    kcal: '368',
    protein: '19',
    lipid: '22',
    carbo: '17',
  },
  {
    name: 'チキンのマリネ',
    kcal: '376',
    protein: '17',
    lipid: '30',
    carbo: '5',
  },
  {
    name: 'サラダチキン',
    kcal: '163',
    protein: '29',
    lipid: '2',
    carbo: '3',
  },
  {
    name: 'ささみのピカタ',
    kcal: '202',
    protein: '23',
    lipid: '10',
    carbo: '3',
  },
  {
    name: 'ささみフライ',
    kcal: '225',
    protein: '18',
    lipid: '12',
    carbo: '9',
  },
  {
    name: 'スパイシーチキン',
    kcal: '322',
    protein: '17',
    lipid: '20',
    carbo: '14',
  },
  {
    name: 'スモークチキン',
    kcal: '170',
    protein: '12',
    lipid: '12',
    carbo: '1',
  },
  {
    name: 'タンドリーチキン',
    kcal: '248',
    protein: '28',
    lipid: '13',
    carbo: '4',
  },
  {
    name: '手羽先唐揚げ',
    kcal: '190',
    protein: '13',
    lipid: '12',
    carbo: '7',
  },
  {
    name: '鶏じゃが',
    kcal: '329',
    protein: '10',
    lipid: '11',
    carbo: '45',
  },
  {
    name: 'チーズタッカルビ',
    kcal: '420',
    protein: '24',
    lipid: '23',
    carbo: '28',
  },
  {
    name: 'チキンカツ',
    kcal: '391',
    protein: '18',
    lipid: '28',
    carbo: '15',
  },
  {
    name: 'チキン南蛮',
    kcal: '408',
    protein: '16',
    lipid: '28',
    carbo: '20',
  },
  {
    name: '鶏天ぷら',
    kcal: '267',
    protein: '22',
    lipid: '15',
    carbo: '9',
  },
  {
    name: '鶏すき焼き',
    kcal: '357',
    protein: '26',
    lipid: '19',
    carbo: '21',
  },
  {
    name: 'ローストチキン',
    kcal: '245',
    protein: '17',
    lipid: '18',
    carbo: '1',
  },
  {
    name: '焼きとり',
    kcal: '145',
    protein: '11',
    lipid: '9',
    carbo: '4',
  },
  {
    name: 'バンバンジー',
    kcal: '156',
    protein: '21',
    lipid: '6',
    carbo: '4',
  },
  {
    name: 'ウインナーソーセージ',
    kcal: '64',
    protein: '3',
    lipid: '6',
    carbo: '1',
  },
  {
    name: '生ハム・プロシュート',
    kcal: '56',
    protein: '5',
    lipid: '4',
    carbo: '0',
  },
  {
    name: 'ベーコンソテー',
    kcal: '61',
    protein: '2',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'ハム',
    kcal: '39',
    protein: '3',
    lipid: '3',
    carbo: '0',
  },
  {
    name: 'ウインナーソテー',
    kcal: '72',
    protein: '3',
    lipid: '7',
    carbo: '1',
  },
  {
    name: 'フランクフルトソーセージ',
    kcal: '164',
    protein: '7',
    lipid: '14',
    carbo: '3',
  },
  {
    name: 'ハムカツ',
    kcal: '65',
    protein: '4',
    lipid: '5',
    carbo: '1',
  },
  {
    name: 'ハムステーキ',
    kcal: '205',
    protein: '17',
    lipid: '15',
    carbo: '1',
  },
  {
    name: 'アスパラガスのベーコン巻き',
    kcal: '156',
    protein: '5',
    lipid: '15',
    carbo: '1',
  },
  {
    name: 'コンビーフ',
    kcal: '203',
    protein: '20',
    lipid: '13',
    carbo: '2',
  },
  {
    name: 'サラミ',
    kcal: '99',
    protein: '5',
    lipid: '9',
    carbo: '0',
  },
  {
    name: '馬刺し',
    kcal: '38',
    protein: '7',
    lipid: '1',
    carbo: '1',
  },
  {
    name: 'フォアグラのソテー',
    kcal: '249',
    protein: '4',
    lipid: '23',
    carbo: '4',
  },
  {
    name: '北京ダック',
    kcal: '93',
    protein: '3',
    lipid: '4',
    carbo: '10',
  },
  {
    name: '鶏ムネ肉の甘酢煮',
    kcal: '335',
    protein: '21',
    lipid: '17',
    carbo: '18',
  },
  {
    name: '鶏ムネ肉の生姜焼き',
    kcal: '334',
    protein: '18',
    lipid: '18',
    carbo: '18',
  },
  {
    name: '鶏ムネ肉の南蛮漬け',
    kcal: '337',
    protein: '18',
    lipid: '22',
    carbo: '13',
  },
  {
    name: '鶏ムネ肉の味噌焼き',
    kcal: '378',
    protein: '17',
    lipid: '22',
    carbo: '20',
  },
  {
    name: 'チーズつくね',
    kcal: '84',
    protein: '5',
    lipid: '4',
    carbo: '5',
  },
  {
    name: 'ジンギスカン',
    kcal: '321',
    protein: '13',
    lipid: '24',
    carbo: '11',
  },
  {
    name: '鴨のコンフィ',
    kcal: '369',
    protein: '25',
    lipid: '13',
    carbo: '30',
  },
  {
    name: '鴨のロースト',
    kcal: '77',
    protein: '14',
    lipid: '2',
    carbo: '0',
  },
  {
    name: '鴨のカルパッチョ',
    kcal: '205',
    protein: '25',
    lipid: '10',
    carbo: '3',
  },
  {
    name: 'クジラベーコン',
    kcal: '150',
    protein: '8',
    lipid: '13',
    carbo: '0',
  },
  {
    name: '鹿肉ステーキ',
    kcal: '224',
    protein: '45',
    lipid: '3',
    carbo: '2',
  },
  {
    name: '鹿肉ロースト',
    kcal: '181',
    protein: '34',
    lipid: '2',
    carbo: '3',
  },
  {
    name: '焼き餃子',
    kcal: '263',
    protein: '14',
    lipid: '14',
    carbo: '18',
  },
  {
    name: 'コロッケ',
    kcal: '179',
    protein: '6',
    lipid: '12',
    carbo: '11',
  },
  {
    name: 'コロッケ（ノンフライヤー）',
    kcal: '155',
    protein: '7',
    lipid: '8',
    carbo: '14',
  },
  {
    name: 'クリームコロッケ',
    kcal: '238',
    protein: '4',
    lipid: '17',
    carbo: '17',
  },
  {
    name: 'コロッケ定食',
    kcal: '756',
    protein: '21',
    lipid: '28',
    carbo: '100',
  },
  {
    name: '餃子定食',
    kcal: '590',
    protein: '20',
    lipid: '16',
    carbo: '86',
  },
  {
    name: '牛肉コロッケ',
    kcal: '159',
    protein: '7',
    lipid: '9',
    carbo: '13',
  },
  {
    name: 'カニクリームコロッケ',
    kcal: '247',
    protein: '5',
    lipid: '17',
    carbo: '17',
  },
  {
    name: 'コロッケパン',
    kcal: '218',
    protein: '5',
    lipid: '8',
    carbo: '31',
  },
  {
    name: 'グラタンコロッケ',
    kcal: '230',
    protein: '6',
    lipid: '13',
    carbo: '22',
  },
  {
    name: 'パンプキンコロッケ',
    kcal: '126',
    protein: '1',
    lipid: '8',
    carbo: '11',
  },
  {
    name: 'カレーコロッケ',
    kcal: '176',
    protein: '2',
    lipid: '12',
    carbo: '14',
  },
  {
    name: 'さつま芋コロッケ',
    kcal: '274',
    protein: '8',
    lipid: '14',
    carbo: '28',
  },
  {
    name: 'チキンコロッケ',
    kcal: '184',
    protein: '7',
    lipid: '11',
    carbo: '14',
  },
  {
    name: '揚げ餃子',
    kcal: '258',
    protein: '14',
    lipid: '14',
    carbo: '18',
  },
  {
    name: '水餃子',
    kcal: '102',
    protein: '5',
    lipid: '4',
    carbo: '13',
  },
  {
    name: 'ミートボール',
    kcal: '217',
    protein: '11',
    lipid: '11',
    carbo: '13',
  },
  {
    name: 'ロールキャベツ',
    kcal: '232',
    protein: '15',
    lipid: '13',
    carbo: '14',
  },
  {
    name: 'シューマイ',
    kcal: '43',
    protein: '2',
    lipid: '2',
    carbo: '3',
  },
  {
    name: '麻婆なす',
    kcal: '435',
    protein: '15',
    lipid: '32',
    carbo: '19',
  },
  {
    name: '麻婆春雨',
    kcal: '308',
    protein: '11',
    lipid: '15',
    carbo: '31',
  },
  {
    name: 'メンチカツ',
    kcal: '244',
    protein: '12',
    lipid: '18',
    carbo: '6',
  },
  {
    name: 'ハンバーグ（デミソース）',
    kcal: '369',
    protein: '19',
    lipid: '27',
    carbo: '9',
  },
  {
    name: 'ハンバーグ（和風ソース）',
    kcal: '389',
    protein: '19',
    lipid: '27',
    carbo: '12',
  },
  {
    name: '豆腐ハンバーグ',
    kcal: '292',
    protein: '23',
    lipid: '19',
    carbo: '4',
  },
  {
    name: '煮込みハンバーグ',
    kcal: '432',
    protein: '23',
    lipid: '27',
    carbo: '22',
  },
  {
    name: 'ハンバーグ（チーズ）',
    kcal: '432',
    protein: '23',
    lipid: '33',
    carbo: '9',
  },
  {
    name: '鶏ひき肉ハンバーグ',
    kcal: '359',
    protein: '26',
    lipid: '21',
    carbo: '10',
  },
  {
    name: 'ひじき入り豆腐ハンバーグ',
    kcal: '66',
    protein: '4',
    lipid: '2',
    carbo: '7',
  },
  {
    name: '豚肉の塩焼き',
    kcal: '265',
    protein: '15',
    lipid: '21',
    carbo: '0',
  },
  {
    name: '小龍包',
    kcal: '65',
    protein: '4',
    lipid: '2',
    carbo: '7',
  },
  {
    name: 'ゆで豚',
    kcal: '263',
    protein: '19',
    lipid: '19',
    carbo: '0',
  },
  {
    name: '揚げシューマイ',
    kcal: '208',
    protein: '10',
    lipid: '12',
    carbo: '13',
  },
  {
    name: '揚げワンタン',
    kcal: '83',
    protein: '4',
    lipid: '5',
    carbo: '5',
  },
  {
    name: '肉味噌',
    kcal: '205',
    protein: '13',
    lipid: '12',
    carbo: '8',
  },
  {
    name: 'ごぼうの肉巻き',
    kcal: '234',
    protein: '17',
    lipid: '11',
    carbo: '11',
  },
  {
    name: 'サケの塩焼き',
    kcal: '171',
    protein: '18',
    lipid: '9',
    carbo: '3',
  },
  {
    name: 'サバの塩焼き',
    kcal: '209',
    protein: '17',
    lipid: '14',
    carbo: '3',
  },
  {
    name: 'サンマの塩焼き',
    kcal: '275',
    protein: '24',
    lipid: '18',
    carbo: '3',
  },
  {
    name: 'ブリの照焼き',
    kcal: '267',
    protein: '18',
    lipid: '17',
    carbo: '6',
  },
  {
    name: 'ホッケのひらき',
    kcal: '412',
    protein: '47',
    lipid: '22',
    carbo: '3',
  },
  {
    name: 'アジの干物',
    kcal: '109',
    protein: '13',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'イカ焼き',
    kcal: '124',
    protein: '15',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'いわしの蒲焼',
    kcal: '239',
    protein: '14',
    lipid: '12',
    carbo: '15',
  },
  {
    name: 'いわしの塩焼き',
    kcal: '79',
    protein: '8',
    lipid: '4',
    carbo: '3',
  },
  {
    name: 'うなぎの蒲焼',
    kcal: '234',
    protein: '18',
    lipid: '17',
    carbo: '3',
  },
  {
    name: 'エビの塩焼き',
    kcal: '9',
    protein: '2',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '牡蠣のバターソテー',
    kcal: '59',
    protein: '1',
    lipid: '4',
    carbo: '3',
  },
  {
    name: '牡蠣のオリーブオイルソテー',
    kcal: '92',
    protein: '4',
    lipid: '6',
    carbo: '4',
  },
  {
    name: 'サケのバター焼き',
    kcal: '204',
    protein: '19',
    lipid: '11',
    carbo: '4',
  },
  {
    name: 'サーモンムニエル',
    kcal: '188',
    protein: '18',
    lipid: '11',
    carbo: '3',
  },
  {
    name: 'サケのホイル焼き',
    kcal: '185',
    protein: '20',
    lipid: '9',
    carbo: '8',
  },
  {
    name: 'サザエの壷焼き',
    kcal: '28',
    protein: '6',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ホタテのソテー',
    kcal: '160',
    protein: '14',
    lipid: '9',
    carbo: '5',
  },
  {
    name: 'ホタテバター焼き',
    kcal: '134',
    protein: '16',
    lipid: '5',
    carbo: '4',
  },
  {
    name: '焼き魚定食',
    kcal: '562',
    protein: '25',
    lipid: '17',
    carbo: '74',
  },
  {
    name: 'ホッケのみりん干し',
    kcal: '235',
    protein: '22',
    lipid: '10',
    carbo: '9',
  },
  {
    name: 'サケの西京焼き',
    kcal: '128',
    protein: '19',
    lipid: '4',
    carbo: '3',
  },
  {
    name: 'サワラの西京焼き',
    kcal: '165',
    protein: '17',
    lipid: '8',
    carbo: '4',
  },
  {
    name: '白身魚のポワレ',
    kcal: '194',
    protein: '8',
    lipid: '15',
    carbo: '5',
  },
  {
    name: '白身魚のホイル焼き',
    kcal: '179',
    protein: '',
    lipid: '',
    carbo: '',
  },
  {
    name: '白身魚の干物',
    kcal: '126',
    protein: '22',
    lipid: '4',
    carbo: '0',
  },
  {
    name: '白身魚のバター焼き',
    kcal: '79',
    protein: '5',
    lipid: '5',
    carbo: '2',
  },
  {
    name: '白身魚のチーズ焼き',
    kcal: '163',
    protein: '18',
    lipid: '8',
    carbo: '4',
  },
  {
    name: '白身魚のグリル',
    kcal: '82',
    protein: '6',
    lipid: '5',
    carbo: '2',
  },
  {
    name: 'サバの味噌煮',
    kcal: '374',
    protein: '29',
    lipid: '23',
    carbo: '7',
  },
  {
    name: 'カレイの煮付け',
    kcal: '121',
    protein: '20',
    lipid: '1',
    carbo: '3',
  },
  {
    name: 'ぶり大根',
    kcal: '211',
    protein: '15',
    lipid: '11',
    carbo: '11',
  },
  {
    name: 'アクアパッツァ',
    kcal: '230',
    protein: '13',
    lipid: '14',
    carbo: '4',
  },
  {
    name: 'あら煮',
    kcal: '161',
    protein: '20',
    lipid: '4',
    carbo: '6',
  },
  {
    name: '金目鯛の煮付け',
    kcal: '222',
    protein: '19',
    lipid: '9',
    carbo: '11',
  },
  {
    name: 'マグロの角煮',
    kcal: '124',
    protein: '19',
    lipid: '1',
    carbo: '6',
  },
  {
    name: 'ホッケの煮付け',
    kcal: '118',
    protein: '11',
    lipid: '3',
    carbo: '6',
  },
  {
    name: 'サバの煮付け',
    kcal: '242',
    protein: '18',
    lipid: '14',
    carbo: '8',
  },
  {
    name: '煮魚定食',
    kcal: '480',
    protein: '16',
    lipid: '7',
    carbo: '81',
  },
  {
    name: '刺身盛り合わせ',
    kcal: '102',
    protein: '14',
    lipid: '4',
    carbo: '1',
  },
  {
    name: 'マグロの刺身',
    kcal: '77',
    protein: '16',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'サーモンの刺身',
    kcal: '100',
    protein: '10',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'カツオのたたき',
    kcal: '115',
    protein: '26',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'ハマチの刺身',
    kcal: '92',
    protein: '8',
    lipid: '6',
    carbo: '1',
  },
  {
    name: 'タコの刺身',
    kcal: '53',
    protein: '11',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'イカソーメン',
    kcal: '42',
    protein: '3',
    lipid: '0',
    carbo: '7',
  },
  {
    name: '白子ポン酢',
    kcal: '39',
    protein: '7',
    lipid: '0',
    carbo: '2',
  },
  {
    name: 'イカの刺身',
    kcal: '31',
    protein: '6',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'イカの塩辛',
    kcal: '23',
    protein: '3',
    lipid: '1',
    carbo: '1',
  },
  {
    name: 'タイの刺身',
    kcal: '25',
    protein: '4',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'タイのカルパッチョ',
    kcal: '126',
    protein: '9',
    lipid: '8',
    carbo: '4',
  },
  {
    name: 'タコのカルパッチョ',
    kcal: '101',
    protein: '11',
    lipid: '5',
    carbo: '2',
  },
  {
    name: 'タコのマリネ',
    kcal: '116',
    protein: '11',
    lipid: '7',
    carbo: '2',
  },
  {
    name: 'タコわさ',
    kcal: '23',
    protein: '5',
    lipid: '0',
    carbo: '1',
  },
  {
    name: '生カキ',
    kcal: '27',
    protein: '3',
    lipid: '1',
    carbo: '2',
  },
  {
    name: 'なめろう',
    kcal: '73',
    protein: '9',
    lipid: '2',
    carbo: '4',
  },
  {
    name: 'ねぎとろ',
    kcal: '157',
    protein: '9',
    lipid: '12',
    carbo: '1',
  },
  {
    name: 'ヒラメのえんがわ',
    kcal: '38',
    protein: '7',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'ヒラメの刺身',
    kcal: '55',
    protein: '10',
    lipid: '2',
    carbo: '0',
  },
  {
    name: 'フグさし（フグの刺身）',
    kcal: '34',
    protein: '8',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ブリの刺身',
    kcal: '156',
    protein: '13',
    lipid: '11',
    carbo: '1',
  },
  {
    name: 'ホタテの刺身',
    kcal: '23',
    protein: '4',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'ホタルイカの沖漬け',
    kcal: '32',
    protein: '3',
    lipid: '1',
    carbo: '1',
  },
  {
    name: 'マグロとアボカドのわさび醤油あえ',
    kcal: '209',
    protein: '20',
    lipid: '12',
    carbo: '6',
  },
  {
    name: 'マグロの山かけ',
    kcal: '72',
    protein: '10',
    lipid: '0',
    carbo: '8',
  },
  {
    name: 'マグロのユッケ',
    kcal: '183',
    protein: '17',
    lipid: '11',
    carbo: '5',
  },
  {
    name: 'マグロ納豆',
    kcal: '95',
    protein: '13',
    lipid: '3',
    carbo: '4',
  },
  {
    name: '刺身定食',
    kcal: '455',
    protein: '22',
    lipid: '7',
    carbo: '72',
  },
  {
    name: '中トロの刺身',
    kcal: '172',
    protein: '10',
    lipid: '14',
    carbo: '0',
  },
  {
    name: 'イカの酢味噌和え',
    kcal: '65',
    protein: '7',
    lipid: '1',
    carbo: '8',
  },
  {
    name: 'うに（生）',
    kcal: '48',
    protein: '6',
    lipid: '2',
    carbo: '1',
  },
  {
    name: 'イカ明太子',
    kcal: '32',
    protein: '6',
    lipid: '1',
    carbo: '1',
  },
  {
    name: 'かぶら寿司',
    kcal: '133',
    protein: '9',
    lipid: '7',
    carbo: '7',
  },
  {
    name: 'カルパッチョ（魚介類）',
    kcal: '144',
    protein: '14',
    lipid: '8',
    carbo: '4',
  },
  {
    name: '白身魚のフライ',
    kcal: '164',
    protein: '16',
    lipid: '9',
    carbo: '4',
  },
  {
    name: 'エビフライ',
    kcal: '104',
    protein: '5',
    lipid: '6',
    carbo: '6',
  },
  {
    name: 'アジフライ',
    kcal: '188',
    protein: '11',
    lipid: '13',
    carbo: '6',
  },
  {
    name: 'カキフライ',
    kcal: '384',
    protein: '9',
    lipid: '30',
    carbo: '16',
  },
  {
    name: 'エビの天ぷら',
    kcal: '55',
    protein: '5',
    lipid: '3',
    carbo: '3',
  },
  {
    name: 'アジの南蛮漬け',
    kcal: '163',
    protein: '10',
    lipid: '8',
    carbo: '9',
  },
  {
    name: 'アジフライ定食',
    kcal: '656',
    protein: '21',
    lipid: '23',
    carbo: '88',
  },
  {
    name: '穴子の天ぷら',
    kcal: '268',
    protein: '12',
    lipid: '19',
    carbo: '11',
  },
  {
    name: 'イカ下足揚げ',
    kcal: '72',
    protein: '5',
    lipid: '4',
    carbo: '2',
  },
  {
    name: 'イカ下足の天ぷら',
    kcal: '91',
    protein: '5',
    lipid: '6',
    carbo: '5',
  },
  {
    name: 'イカのから揚げ',
    kcal: '178',
    protein: '15',
    lipid: '11',
    carbo: '4',
  },
  {
    name: 'イカの天ぷら',
    kcal: '86',
    protein: '5',
    lipid: '5',
    carbo: '4',
  },
  {
    name: 'イカフライ',
    kcal: '175',
    protein: '10',
    lipid: '12',
    carbo: '7',
  },
  {
    name: 'イカリングフライ',
    kcal: '196',
    protein: '12',
    lipid: '12',
    carbo: '8',
  },
  {
    name: 'エビカツ',
    kcal: '277',
    protein: '12',
    lipid: '16',
    carbo: '20',
  },
  {
    name: 'エビクリームコロッケ',
    kcal: '280',
    protein: '10',
    lipid: '15',
    carbo: '26',
  },
  {
    name: 'エビフライ定食',
    kcal: '595',
    protein: '30',
    lipid: '14',
    carbo: '84',
  },
  {
    name: '海鮮かき揚げ丼',
    kcal: '770',
    protein: '19',
    lipid: '17',
    carbo: '130',
  },
  {
    name: 'かき揚げ丼',
    kcal: '693',
    protein: '13',
    lipid: '11',
    carbo: '129',
  },
  {
    name: 'カキフライ定食',
    kcal: '651',
    protein: '21',
    lipid: '22',
    carbo: '89',
  },
  {
    name: 'キスの天ぷら',
    kcal: '40',
    protein: '3',
    lipid: '2',
    carbo: '2',
  },
  {
    name: 'サーモンフライ',
    kcal: '207',
    protein: '19',
    lipid: '12',
    carbo: '4',
  },
  {
    name: '魚のすり身揚げ',
    kcal: '61',
    protein: '6',
    lipid: '3',
    carbo: '2',
  },
  {
    name: 'サケの南蛮漬け',
    kcal: '204',
    protein: '19',
    lipid: '8',
    carbo: '9',
  },
  {
    name: 'サバの南蛮漬け',
    kcal: '261',
    protein: '15',
    lipid: '16',
    carbo: '9',
  },
  {
    name: 'シシャモの南蛮漬け',
    kcal: '224',
    protein: '13',
    lipid: '12',
    carbo: '13',
  },
  {
    name: 'シシャモフライ',
    kcal: '182',
    protein: '13',
    lipid: '11',
    carbo: '6',
  },
  {
    name: '天ぷら定食',
    kcal: '716',
    protein: '21',
    lipid: '27',
    carbo: '94',
  },
  {
    name: 'ワカサギの天ぷら',
    kcal: '86',
    protein: '5',
    lipid: '5',
    carbo: '5',
  },
  {
    name: 'ワカサギのマリネ',
    kcal: '174',
    protein: '9',
    lipid: '13',
    carbo: '4',
  },
  {
    name: 'ワカサギの南蛮漬',
    kcal: '208',
    protein: '10',
    lipid: '13',
    carbo: '9',
  },
  {
    name: 'エビのチリソース炒め',
    kcal: '262',
    protein: '21',
    lipid: '12',
    carbo: '11',
  },
  {
    name: '八宝菜',
    kcal: '296',
    protein: '23',
    lipid: '15',
    carbo: '16',
  },
  {
    name: 'ガーリックシュリンプ',
    kcal: '198',
    protein: '18',
    lipid: '13',
    carbo: '1',
  },
  {
    name: 'イカの炒めもの',
    kcal: '138',
    protein: '13',
    lipid: '7',
    carbo: '4',
  },
  {
    name: 'アサリのバター炒め',
    kcal: '94',
    protein: '4',
    lipid: '6',
    carbo: '1',
  },
  {
    name: '青菜とホタテの炒めもの',
    kcal: '121',
    protein: '9',
    lipid: '7',
    carbo: '5',
  },
  {
    name: 'イカ下足のピリ辛炒め',
    kcal: '219',
    protein: '11',
    lipid: '9',
    carbo: '22',
  },
  {
    name: 'エビのマヨネーズ炒め',
    kcal: '159',
    protein: '8',
    lipid: '10',
    carbo: '10',
  },
  {
    name: 'カニ風味かまぼこ',
    kcal: '9',
    protein: '1',
    lipid: '0',
    carbo: '1',
  },
  {
    name: '魚肉ソーセージ',
    kcal: '137',
    protein: '10',
    lipid: '6',
    carbo: '11',
  },
  {
    name: 'さつま揚げ',
    kcal: '90',
    protein: '8',
    lipid: '2',
    carbo: '9',
  },
  {
    name: 'かまぼこ',
    kcal: '38',
    protein: '5',
    lipid: '0',
    carbo: '4',
  },
  {
    name: 'ちくわの天ぷら',
    kcal: '71',
    protein: '4',
    lipid: '4',
    carbo: '6',
  },
  {
    name: 'ちくわの磯辺揚げ',
    kcal: '94',
    protein: '4',
    lipid: '6',
    carbo: '7',
  },
  {
    name: 'アサリのワイン蒸し',
    kcal: '110',
    protein: '4',
    lipid: '9',
    carbo: '1',
  },
  {
    name: 'イカの燻製',
    kcal: '41',
    protein: '7',
    lipid: '0',
    carbo: '3',
  },
  {
    name: 'エイヒレ',
    kcal: '17',
    protein: '4',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'チーズかまぼこ',
    kcal: '33',
    protein: '3',
    lipid: '1',
    carbo: '3',
  },
  {
    name: '竹輪きゅうり',
    kcal: '40',
    protein: '4',
    lipid: '1',
    carbo: '5',
  },
  {
    name: 'つみれ',
    kcal: '34',
    protein: '4',
    lipid: '1',
    carbo: '2',
  },
  {
    name: 'なると',
    kcal: '128',
    protein: '12',
    lipid: '1',
    carbo: '19',
  },
  {
    name: 'はんぺん',
    kcal: '75',
    protein: '8',
    lipid: '1',
    carbo: '9',
  },
  {
    name: 'まる天',
    kcal: '118',
    protein: '10',
    lipid: '5',
    carbo: '8',
  },
  {
    name: 'シーチキン（缶詰め）',
    kcal: '230',
    protein: '15',
    lipid: '19',
    carbo: '0',
  },
  {
    name: 'ツナフレーク缶（オイル無添加）',
    kcal: '57',
    protein: '13',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'サバ味付け（缶詰め）',
    kcal: '409',
    protein: '41',
    lipid: '24',
    carbo: '8',
  },
  {
    name: 'サンマ蒲焼（缶詰め）',
    kcal: '225',
    protein: '17',
    lipid: '13',
    carbo: '10',
  },
  {
    name: 'サバ味噌煮（缶詰め）',
    kcal: '412',
    protein: '31',
    lipid: '26',
    carbo: '13',
  },
  {
    name: 'いわし蒲焼（缶詰め）',
    kcal: '363',
    protein: '24',
    lipid: '23',
    carbo: '14',
  },
  {
    name: 'アーモンドフィッシュ',
    kcal: '310',
    protein: '17',
    lipid: '15',
    carbo: '26',
  },
  {
    name: 'アサリの酒蒸し',
    kcal: '41',
    protein: '5',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'あじのたたき丼',
    kcal: '534',
    protein: '23',
    lipid: '5',
    carbo: '94',
  },
  {
    name: 'あたりめ',
    kcal: '22',
    protein: '5',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'イカと里芋の煮物',
    kcal: '151',
    protein: '10',
    lipid: '1',
    carbo: '27',
  },
  {
    name: 'イカナゴのくぎ煮',
    kcal: '95',
    protein: '9',
    lipid: '3',
    carbo: '7',
  },
  {
    name: 'イクラ',
    kcal: '41',
    protein: '5',
    lipid: '2',
    carbo: '0',
  },
  {
    name: 'さきいか',
    kcal: '56',
    protein: '9',
    lipid: '1',
    carbo: '4',
  },
  {
    name: 'カキオイル漬',
    kcal: '366',
    protein: '6',
    lipid: '34',
    carbo: '6',
  },
  {
    name: '鯛めし（炊き込み）',
    kcal: '274',
    protein: '18',
    lipid: '3',
    carbo: '40',
  },
  {
    name: '蒸し穴子',
    kcal: '97',
    protein: '9',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'マグロとアボカドのサラダ',
    kcal: '210',
    protein: '9',
    lipid: '17',
    carbo: '8',
  },
  {
    name: 'ゆでエビ',
    kcal: '22',
    protein: '5',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ゆでガニ',
    kcal: '32',
    protein: '7',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'わけぎとイカの酢みそ和え',
    kcal: '73',
    protein: '8',
    lipid: '1',
    carbo: '9',
  },
  {
    name: 'マグロの唐揚げ',
    kcal: '197',
    protein: '22',
    lipid: '9',
    carbo: '4',
  },
  {
    name: 'かずのこ',
    kcal: '45',
    protein: '8',
    lipid: '2',
    carbo: '0',
  },
  {
    name: 'ムール貝の白ワイン蒸し',
    kcal: '127',
    protein: '6',
    lipid: '6',
    carbo: '8',
  },
  {
    name: '酢ダコ',
    kcal: '101',
    protein: '15',
    lipid: '1',
    carbo: '10',
  },
  {
    name: 'ゆでたまご',
    kcal: '91',
    protein: '8',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'たまご焼き',
    kcal: '90',
    protein: '5',
    lipid: '6',
    carbo: '2',
  },
  {
    name: '目玉焼き',
    kcal: '83',
    protein: '5',
    lipid: '6',
    carbo: '0',
  },
  {
    name: '生たまご',
    kcal: '77',
    protein: '6',
    lipid: '5',
    carbo: '0',
  },
  {
    name: 'スクランブルエッグ',
    kcal: '115',
    protein: '6',
    lipid: '10',
    carbo: '1',
  },
  {
    name: '温泉たまご',
    kcal: '77',
    protein: '6',
    lipid: '5',
    carbo: '0',
  },
  {
    name: 'オムレツ',
    kcal: '174',
    protein: '11',
    lipid: '13',
    carbo: '2',
  },
  {
    name: '煮たまご（味付けたまご）',
    kcal: '90',
    protein: '6',
    lipid: '5',
    carbo: '2',
  },
  {
    name: '錦糸たまご',
    kcal: '30',
    protein: '2',
    lipid: '2',
    carbo: '0',
  },
  {
    name: 'だし巻きたまご',
    kcal: '128',
    protein: '9',
    lipid: '9',
    carbo: '2',
  },
  {
    name: 'うずらたまご水煮（缶詰め）',
    kcal: '18',
    protein: '1',
    lipid: '1',
    carbo: '0',
  },
  {
    name: '伊達巻き',
    kcal: '59',
    protein: '4',
    lipid: '2',
    carbo: '5',
  },
  {
    name: 'オムライス',
    kcal: '700',
    protein: '23',
    lipid: '30',
    carbo: '79',
  },
  {
    name: 'オムそば',
    kcal: '601',
    protein: '19',
    lipid: '26',
    carbo: '69',
  },
  {
    name: 'オムハヤシ',
    kcal: '923',
    protein: '29',
    lipid: '42',
    carbo: '99',
  },
  {
    name: '茶碗蒸し',
    kcal: '117',
    protein: '13',
    lipid: '3',
    carbo: '8',
  },
  {
    name: 'ハムエッグ',
    kcal: '145',
    protein: '10',
    lipid: '11',
    carbo: '1',
  },
  {
    name: 'ハムエッグトースト',
    kcal: '302',
    protein: '18',
    lipid: '17',
    carbo: '20',
  },
  {
    name: 'ハムエッグ',
    kcal: '145',
    protein: '10',
    lipid: '11',
    carbo: '1',
  },
  {
    name: '納豆',
    kcal: '90',
    protein: '7',
    lipid: '5',
    carbo: '5',
  },
  {
    name: '枝豆',
    kcal: '34',
    protein: '3',
    lipid: '2',
    carbo: '2',
  },
  {
    name: '冷奴',
    kcal: '62',
    protein: '6',
    lipid: '3',
    carbo: '2',
  },
  {
    name: '麻婆豆腐',
    kcal: '278',
    protein: '16',
    lipid: '20',
    carbo: '7',
  },
  {
    name: '揚げだし豆腐',
    kcal: '186',
    protein: '8',
    lipid: '11',
    carbo: '13',
  },
  {
    name: 'たまご豆腐',
    kcal: '79',
    protein: '6',
    lipid: '5',
    carbo: '2',
  },
  {
    name: '揚げだし豆腐',
    kcal: '258',
    protein: '12',
    lipid: '15',
    carbo: '17',
  },
  {
    name: '豆腐サラダ',
    kcal: '77',
    protein: '7',
    lipid: '4',
    carbo: '3',
  },
  {
    name: '豆腐ステーキ',
    kcal: '195',
    protein: '12',
    lipid: '12',
    carbo: '9',
  },
  {
    name: '豆腐とアボカドのサラダ',
    kcal: '64',
    protein: '4',
    lipid: '4',
    carbo: '3',
  },
  {
    name: '豆腐となすの揚げ浸し',
    kcal: '246',
    protein: '7',
    lipid: '19',
    carbo: '9',
  },
  {
    name: '湯豆腐',
    kcal: '105',
    protein: '9',
    lipid: '5',
    carbo: '8',
  },
  {
    name: '春菊の白和え',
    kcal: '82',
    protein: '6',
    lipid: '5',
    carbo: '6',
  },
  {
    name: '胡麻豆腐',
    kcal: '76',
    protein: '2',
    lipid: '4',
    carbo: '9',
  },
  {
    name: 'おから',
    kcal: '89',
    protein: '5',
    lipid: '3',
    carbo: '11',
  },
  {
    name: '厚揚と糸こんにゃくのきんぴら',
    kcal: '148',
    protein: '7',
    lipid: '10',
    carbo: '8',
  },
  {
    name: '湯葉（ゆば）',
    kcal: '116',
    protein: '11',
    lipid: '7',
    carbo: '2',
  },
  {
    name: '無調整豆乳',
    kcal: '92',
    protein: '7',
    lipid: '4',
    carbo: '6',
  },
  {
    name: '豆乳（調整豆乳）',
    kcal: '128',
    protein: '6',
    lipid: '7',
    carbo: '10',
  },
  {
    name: 'ほうれん草と大豆の煮浸し',
    kcal: '93',
    protein: '7',
    lipid: '4',
    carbo: '6',
  },
  {
    name: '信田巻き',
    kcal: '151',
    protein: '9',
    lipid: '8',
    carbo: '9',
  },
  {
    name: '高野豆腐の照り焼き',
    kcal: '162',
    protein: '8',
    lipid: '9',
    carbo: '11',
  },
  {
    name: '油揚げ',
    kcal: '82',
    protein: '5',
    lipid: '7',
    carbo: '0',
  },
  {
    name: '高野豆腐の肉巻き照り焼き',
    kcal: '282',
    protein: '12',
    lipid: '20',
    carbo: '11',
  },
  {
    name: '焼き豆腐',
    kcal: '264',
    protein: '23',
    lipid: '17',
    carbo: '3',
  },
  {
    name: 'ビール（350ml缶）',
    kcal: '140',
    protein: '1',
    lipid: '0',
    carbo: '11',
  },
  {
    name: 'ビール（500ml缶）',
    kcal: '200',
    protein: '2',
    lipid: '0',
    carbo: '16',
  },
  {
    name: '発泡酒（350ml缶）',
    kcal: '158',
    protein: '0',
    lipid: '0',
    carbo: '13',
  },
  {
    name: '発泡酒（500ml缶）',
    kcal: '225',
    protein: '1',
    lipid: '0',
    carbo: '18',
  },
  {
    name: 'ビール（中瓶）',
    kcal: '200',
    protein: '2',
    lipid: '0',
    carbo: '16',
  },
  {
    name: 'ビール（大瓶）',
    kcal: '252',
    protein: '2',
    lipid: '0',
    carbo: '20',
  },
  {
    name: 'シャンディーガフ',
    kcal: '160',
    protein: '0',
    lipid: '0',
    carbo: '32',
  },
  {
    name: '甘酒',
    kcal: '122',
    protein: '3',
    lipid: '0',
    carbo: '28',
  },
  {
    name: '日本酒',
    kcal: '185',
    protein: '1',
    lipid: '0',
    carbo: '7',
  },
  {
    name: '焼酎ロック',
    kcal: '88',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '焼酎水割り',
    kcal: '117',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '焼酎お湯割り',
    kcal: '117',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '焼酎ボトル',
    kcal: '1051',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '生ビール（中ジョッキ）',
    kcal: '200',
    protein: '2',
    lipid: '0',
    carbo: '16',
  },
  {
    name: '缶チュウハイ',
    kcal: '189',
    protein: '0',
    lipid: '0',
    carbo: '16',
  },
  {
    name: '生レモンサワー',
    kcal: '143',
    protein: '0',
    lipid: '0',
    carbo: '6',
  },
  {
    name: '生グレープフルーツサワー',
    kcal: '157',
    protein: '1',
    lipid: '0',
    carbo: '10',
  },
  {
    name: '梅酒',
    kcal: '140',
    protein: '0',
    lipid: '0',
    carbo: '19',
  },
  {
    name: '梅酒ソーダ',
    kcal: '186',
    protein: '0',
    lipid: '0',
    carbo: '30',
  },
  {
    name: 'サワー',
    kcal: '117',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ウイスキー（ボトル）',
    kcal: '1659',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ウイスキーシングル',
    kcal: '71',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ウイスキーダブル',
    kcal: '142',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ブランデー',
    kcal: '71',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ホットウイスキー',
    kcal: '107',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ジントニック',
    kcal: '169',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'カシスオレンジ',
    kcal: '144',
    protein: '2',
    lipid: '0',
    carbo: '23',
  },
  {
    name: 'サングリア',
    kcal: '107',
    protein: '0',
    lipid: '0',
    carbo: '10',
  },
  {
    name: 'ウォッカ',
    kcal: '108',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'カシスウーロン',
    kcal: '81',
    protein: '1',
    lipid: '0',
    carbo: '7',
  },
  {
    name: 'カルーアミルク',
    kcal: '167',
    protein: '4',
    lipid: '5',
    carbo: '19',
  },
  {
    name: 'カシスグレープフルーツ',
    kcal: '141',
    protein: '1',
    lipid: '0',
    carbo: '22',
  },
  {
    name: 'カシスソーダ',
    kcal: '81',
    protein: '1',
    lipid: '0',
    carbo: '7',
  },
  {
    name: 'カシスミルク',
    kcal: '182',
    protein: '5',
    lipid: '6',
    carbo: '14',
  },
  {
    name: 'ジン',
    kcal: '85',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'スクリュードライバー',
    kcal: '122',
    protein: '1',
    lipid: '0',
    carbo: '13',
  },
  {
    name: 'ソルティードッグ',
    kcal: '147',
    protein: '1',
    lipid: '0',
    carbo: '10',
  },
  {
    name: 'ブラッディマリー',
    kcal: '127',
    protein: '1',
    lipid: '0',
    carbo: '5',
  },
  {
    name: 'モスコミュール',
    kcal: '153',
    protein: '0',
    lipid: '0',
    carbo: '12',
  },
  {
    name: 'モヒート',
    kcal: '143',
    protein: '0',
    lipid: '0',
    carbo: '9',
  },
  {
    name: 'グラスワイン（赤）',
    kcal: '73',
    protein: '0',
    lipid: '0',
    carbo: '2',
  },
  {
    name: 'グラスワイン（白）',
    kcal: '73',
    protein: '0',
    lipid: '0',
    carbo: '2',
  },
  {
    name: 'グラスワイン（ロゼ）',
    kcal: '77',
    protein: '0',
    lipid: '0',
    carbo: '4',
  },
  {
    name: 'ワイン（赤）ボトル',
    kcal: '536',
    protein: '1',
    lipid: '0',
    carbo: '11',
  },
  {
    name: 'ワイン（白）ボトル',
    kcal: '526',
    protein: '1',
    lipid: '0',
    carbo: '14',
  },
  {
    name: 'テキーラ',
    kcal: '67',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ハイボール',
    kcal: '119',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ジンジャーハイボール',
    kcal: '308',
    protein: '0',
    lipid: '0',
    carbo: '46',
  },
  {
    name: 'シャンパン',
    kcal: '73',
    protein: '0',
    lipid: '0',
    carbo: '2',
  },
  {
    name: 'シャンパン（ボトル）',
    kcal: '526',
    protein: '1',
    lipid: '0',
    carbo: '14',
  },
  {
    name: 'ホッピー',
    kcal: '151',
    protein: '0',
    lipid: '0',
    carbo: '4',
  },
  {
    name: 'ホットワイン',
    kcal: '144',
    protein: '1',
    lipid: '0',
    carbo: '11',
  },
  {
    name: '牛乳',
    kcal: '121',
    protein: '6',
    lipid: '7',
    carbo: '9',
  },
  {
    name: '低脂肪牛乳',
    kcal: '83',
    protein: '7',
    lipid: '2',
    carbo: '10',
  },
  {
    name: '無脂肪牛乳',
    kcal: '66',
    protein: '7',
    lipid: '0',
    carbo: '9',
  },
  {
    name: '濃厚牛乳',
    kcal: '131',
    protein: '6',
    lipid: '8',
    carbo: '9',
  },
  {
    name: '牛乳プリン',
    kcal: '86',
    protein: '4',
    lipid: '3',
    carbo: '11',
  },
  {
    name: 'ヨーグルト（無糖）',
    kcal: '62',
    protein: '4',
    lipid: '3',
    carbo: '5',
  },
  {
    name: 'ヨーグルト（加糖）',
    kcal: '67',
    protein: '4',
    lipid: '0',
    carbo: '12',
  },
  {
    name: 'ヨーグルト（無脂肪）',
    kcal: '34',
    protein: '3',
    lipid: '0',
    carbo: '5',
  },
  {
    name: 'ヨーグルト（低糖）',
    kcal: '64',
    protein: '3',
    lipid: '3',
    carbo: '8',
  },
  {
    name: 'ヨーグルト（低脂肪）',
    kcal: '36',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: 'ヨーグルト（低糖・低脂肪）',
    kcal: '54',
    protein: '4',
    lipid: '1',
    carbo: '8',
  },
  {
    name: 'ヨーグルト（ハチミツ入り）',
    kcal: '121',
    protein: '4',
    lipid: '3',
    carbo: '21',
  },
  {
    name: 'ヨーグルト（ジャムトッピング）',
    kcal: '62',
    protein: '4',
    lipid: '3',
    carbo: '5',
  },
  {
    name: 'プロセスチーズ',
    kcal: '68',
    protein: '5',
    lipid: '5',
    carbo: '0',
  },
  {
    name: 'ホイップクリーム',
    kcal: '76',
    protein: '0',
    lipid: '6',
    carbo: '5',
  },
  {
    name: 'モッツァレラチーズ',
    kcal: '55',
    protein: '4',
    lipid: '4',
    carbo: '1',
  },
  {
    name: 'フルーツヨーグルト',
    kcal: '78',
    protein: '4',
    lipid: '0',
    carbo: '16',
  },
  {
    name: 'フルーツヨーグルト（無糖）',
    kcal: '62',
    protein: '4',
    lipid: '3',
    carbo: '5',
  },
  {
    name: 'アロエヨーグルト',
    kcal: '47',
    protein: '3',
    lipid: '0',
    carbo: '8',
  },
  {
    name: 'アロエヨーグルト（低脂肪）',
    kcal: '32',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: 'アロエヨーグルト（無脂肪）',
    kcal: '30',
    protein: '3',
    lipid: '0',
    carbo: '4',
  },
  {
    name: 'エダムチーズ',
    kcal: '89',
    protein: '7',
    lipid: '6',
    carbo: '0',
  },
  {
    name: 'エメンタールチーズ',
    kcal: '107',
    protein: '7',
    lipid: '8',
    carbo: '0',
  },
  {
    name: 'おからヨーグルト',
    kcal: '125',
    protein: '7',
    lipid: '5',
    carbo: '13',
  },
  {
    name: 'カテージチーズ',
    kcal: '16',
    protein: '2',
    lipid: '1',
    carbo: '0',
  },
  {
    name: 'カマンベールチーズ',
    kcal: '62',
    protein: '4',
    lipid: '5',
    carbo: '0',
  },
  {
    name: 'きな粉ヨーグルト',
    kcal: '135',
    protein: '6',
    lipid: '5',
    carbo: '18',
  },
  {
    name: 'クリープ',
    kcal: '16',
    protein: '0',
    lipid: '1',
    carbo: '2',
  },
  {
    name: 'クリームチーズ',
    kcal: '69',
    protein: '2',
    lipid: '7',
    carbo: '1',
  },
  {
    name: 'スキムミルク',
    kcal: '29',
    protein: '3',
    lipid: '0',
    carbo: '4',
  },
  {
    name: 'スモークチーズ',
    kcal: '87',
    protein: '6',
    lipid: '7',
    carbo: '0',
  },
  {
    name: 'チーズ盛り合わせ',
    kcal: '478',
    protein: '17',
    lipid: '19',
    carbo: '60',
  },
  {
    name: 'チェダーチーズ',
    kcal: '106',
    protein: '6',
    lipid: '9',
    carbo: '0',
  },
  {
    name: '生クリーム',
    kcal: '65',
    protein: '0',
    lipid: '7',
    carbo: '1',
  },
  {
    name: 'バナナヨーグルト',
    kcal: '153',
    protein: '6',
    lipid: '5',
    carbo: '23',
  },
  {
    name: 'パルメザンチーズ（粉チーズ）',
    kcal: '38',
    protein: '4',
    lipid: '3',
    carbo: '0',
  },
  {
    name: 'コーヒー（ブラック）',
    kcal: '7',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'カフェオレ（砂糖なし）',
    kcal: '70',
    protein: '4',
    lipid: '4',
    carbo: '5',
  },
  {
    name: 'アイスコーヒー（ブラック）',
    kcal: '8',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'アイスカフェオレ（砂糖なし）',
    kcal: '71',
    protein: '4',
    lipid: '4',
    carbo: '6',
  },
  {
    name: 'アイスカフェラテ',
    kcal: '102',
    protein: '5',
    lipid: '6',
    carbo: '7',
  },
  {
    name: 'エスプレッソコーヒー',
    kcal: '1',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'カフェオレ（缶）',
    kcal: '72',
    protein: '1',
    lipid: '1',
    carbo: '16',
  },
  {
    name: '缶コーヒー（加糖）',
    kcal: '72',
    protein: '1',
    lipid: '1',
    carbo: '16',
  },
  {
    name: '缶コーヒー（微糖）',
    kcal: '68',
    protein: '3',
    lipid: '0',
    carbo: '11',
  },
  {
    name: '缶コーヒー（無糖）',
    kcal: '0',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '緑茶',
    kcal: '3',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '紅茶',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '麦茶',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'ココアラテ',
    kcal: '129',
    protein: '5',
    lipid: '6',
    carbo: '16',
  },
  {
    name: 'こぶ茶',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'ジャスミン茶',
    kcal: '0',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'しょうが紅茶',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'しょうがココア',
    kcal: '28',
    protein: '2',
    lipid: '2',
    carbo: '5',
  },
  {
    name: 'ジンジャーラテ',
    kcal: '96',
    protein: '5',
    lipid: '5',
    carbo: '8',
  },
  {
    name: 'チャイ',
    kcal: '67',
    protein: '3',
    lipid: '4',
    carbo: '5',
  },
  {
    name: '豆乳ココア',
    kcal: '142',
    protein: '8',
    lipid: '9',
    carbo: '13',
  },
  {
    name: '豆乳ラテ',
    kcal: '97',
    protein: '5',
    lipid: '5',
    carbo: '7',
  },
  {
    name: 'バターコーヒー',
    kcal: '53',
    protein: '0',
    lipid: '5',
    carbo: '1',
  },
  {
    name: 'はと麦茶',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'バナナ豆乳',
    kcal: '124',
    protein: '6',
    lipid: '3',
    carbo: '19',
  },
  {
    name: 'プーアール茶',
    kcal: '3',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'フラぺチーノ',
    kcal: '345',
    protein: '5',
    lipid: '25',
    carbo: '28',
  },
  {
    name: 'ほうじ茶',
    kcal: '3',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ほうじ茶ラテ',
    kcal: '121',
    protein: '6',
    lipid: '7',
    carbo: '9',
  },
  {
    name: '抹茶',
    kcal: '6',
    protein: '1',
    lipid: '0',
    carbo: '1',
  },
  {
    name: '抹茶オレ',
    kcal: '130',
    protein: '7',
    lipid: '7',
    carbo: '10',
  },
  {
    name: '抹茶豆乳',
    kcal: '125',
    protein: '7',
    lipid: '7',
    carbo: '10',
  },
  {
    name: '抹茶ラテ',
    kcal: '134',
    protein: '7',
    lipid: '7',
    carbo: '10',
  },
  {
    name: 'ミルクココア',
    kcal: '148',
    protein: '8',
    lipid: '9',
    carbo: '13',
  },
  {
    name: 'ミルクティー',
    kcal: '68',
    protein: '3',
    lipid: '4',
    carbo: '5',
  },
  {
    name: 'ゆず茶',
    kcal: '40',
    protein: '0',
    lipid: '0',
    carbo: '13',
  },
  {
    name: 'ルイボスティ',
    kcal: '0',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'レモンティー',
    kcal: '4',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: '紅茶オレ',
    kcal: '61',
    protein: '3',
    lipid: '3',
    carbo: '4',
  },
  {
    name: 'アイスティー（ストレート）',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'アイスレモンティー',
    kcal: '5',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'アイスロイヤルミルクティー',
    kcal: '137',
    protein: '7',
    lipid: '8',
    carbo: '10',
  },
  {
    name: 'ウーロン茶（200ml）',
    kcal: '0',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'ウーロン茶（500ml）',
    kcal: '0',
    protein: '0',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'お茶（500ml）',
    kcal: '10',
    protein: '1',
    lipid: '0',
    carbo: '1',
  },
  {
    name: 'カフェモカ',
    kcal: '193',
    protein: '6',
    lipid: '11',
    carbo: '17',
  },
  {
    name: 'カフェラテ',
    kcal: '102',
    protein: '5',
    lipid: '6',
    carbo: '7',
  },
  {
    name: 'カプチーノ',
    kcal: '43',
    protein: '2',
    lipid: '2',
    carbo: '4',
  },
  {
    name: 'キャラメルマキアート',
    kcal: '153',
    protein: '5',
    lipid: '8',
    carbo: '16',
  },
  {
    name: '黒豆茶',
    kcal: '2',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: '玄米茶',
    kcal: '0',
    protein: '0',
    lipid: '0',
    carbo: '0',
  },
  {
    name: 'コーヒーフラッペ',
    kcal: '170',
    protein: '6',
    lipid: '5',
    carbo: '27',
  },
  {
    name: 'コーヒーフロート',
    kcal: '152',
    protein: '4',
    lipid: '6',
    carbo: '20',
  },
  {
    name: 'コーヒーフラペチーノ',
    kcal: '153',
    protein: '5',
    lipid: '4',
    carbo: '25',
  },
  {
    name: '紅茶（缶）',
    kcal: '56',
    protein: '0',
    lipid: '0',
    carbo: '14',
  },
  {
    name: '紅茶（缶）ミルクティー',
    kcal: '130',
    protein: '3',
    lipid: '4',
    carbo: '22',
  },
  {
    name: '紅茶（缶）レモンティー',
    kcal: '98',
    protein: '0',
    lipid: '0',
    carbo: '25',
  }
])
