User.create!(
  email: 'test@test.com',
  password: '123456',
  first_name: '将暉',
  first_name_kana: 'マサキ',
  last_name: '菅田',
  last_name_kana: 'スダ',
  phone_number: '09012345678',
  birthday: '1993-02-21', 
  sex: 'male',
  height: '176',
  weight: '65',
)

foods = Food.create!([
  {
    name: '白ご飯（白米・100g）',
    kcal: '168',
    protein: '3',
    lipid: '0',
    carbo: '37',
  },
  {
    name: '白ご飯（白米・120g）',
    kcal: '202',
    protein: '3',
    lipid: '0',
    carbo: '45',
  },
  {
    name: '白ご飯（白米・150g）',
    kcal: '252',
    protein: '4',
    lipid: '1',
    carbo: '56',
  },
  {
    name: '白ご飯（白米・180g）',
    kcal: '302',
    protein: '5',
    lipid: '1',
    carbo: '67',
  },
  {
    name: '白ご飯（白米・ 200g）',
    kcal: '336',
    protein: '5',
    lipid: '1',
    carbo: '74',
  },
  {
    name: '白ご飯（白米・ 300g）',
    kcal: '504',
    protein: '8',
    lipid: '1',
    carbo: '111',
  },
  {
    name: '玄米ご飯（100g）',
    kcal: '158',
    protein: '3',
    lipid: '1',
    carbo: '34',
  },
  {
    name: '玄米ご飯（120g）',
    kcal: '198',
    protein: '3',
    lipid: '1',
    carbo: '42',
  },
  {
    name: '玄米ご飯（150g）',
    kcal: '257',
    protein: '4',
    lipid: '2',
    carbo: '56',
  },
  {
    name: '玄米ご飯（180g）',
    kcal: '297',
    protein: '5',
    lipid: '2',
    carbo: '64',
  },
  {
    name: '玄米ご飯（200g）',
    kcal: '337',
    protein: '6',
    lipid: '2',
    carbo: '73',
  },
  {
    name: '玄米ご飯（300g）',
    kcal: '495',
    protein: '9',
    lipid: '3',
    carbo: '107',
  },
  {
    name: 'おにぎり（サケ）',
    kcal: '191',
    protein: '6',
    lipid: '1',
    carbo: '38',
  },
  {
    name: 'おにぎり（梅）',
    kcal: '173',
    protein: '3',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（昆布）',
    kcal: '195',
    protein: '4',
    lipid: '1',
    carbo: '43',
  },
  {
    name: 'おにぎり（ツナマヨ）',
    kcal: '240',
    protein: '5',
    lipid: '7',
    carbo: '38',
  },
  {
    name: 'おにぎり（エビマヨ）',
    kcal: '206',
    protein: '5',
    lipid: '3',
    carbo: '38',
  },
  {
    name: 'おにぎり（明太子）',
    kcal: '182',
    protein: '5',
    lipid: '1',
    carbo: '38',
  },
  {
    name: 'おにぎり（たらこ）',
    kcal: '187',
    protein: '6',
    lipid: '1',
    carbo: '38',
  },
  {
    name: 'おにぎり（塩）',
    kcal: '168',
    protein: '3',
    lipid: '0',
    carbo: '37',
  },
  {
    name: 'おにぎり（高菜）',
    kcal: '173',
    protein: '3',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（鶏五目）',
    kcal: '240',
    protein: '7',
    lipid: '3',
    carbo: '44',
  },
  {
    name: 'おにぎり（煮たまご）',
    kcal: '222',
    protein: '7',
    lipid: '3',
    carbo: '40',
  },
  {
    name: 'おにぎり（おかか）',
    kcal: '176',
    protein: '4',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（梅しそひじき）',
    kcal: '172',
    protein: '3',
    lipid: '0',
    carbo: '38',
  },
  {
    name: 'おにぎり（ねぎとろ）',
    kcal: '224',
    protein: '6',
    lipid: '4',
    carbo: '39',
  },
  {
    name: 'おにぎり（明太子マヨネーズ）',
    kcal: '236',
    protein: '5',
    lipid: '7',
    carbo: '38',
  },
  {
    name: 'おにぎり（牛カルビマヨネーズ）',
    kcal: '342',
    protein: '7',
    lipid: '16',
    carbo: '39',
  },
  {
    name: 'おにぎり（すじこ）',
    kcal: '212',
    protein: '8',
    lipid: '3',
    carbo: '38',
  },
  {
    name: 'おにぎり（天むす）',
    kcal: '218',
    protein: '6',
    lipid: '4',
    carbo: '39',
  },
  {
    name: 'お茶漬け',
    kcal: '274',
    protein: '5',
    lipid: '1',
    carbo: '58',
  },
  {
    name: 'お茶漬け（鯛茶漬け）',
    kcal: '287',
    protein: '8',
    lipid: '2',
    carbo: '57',
  },
  {
    name: 'お茶漬け（うなぎ）',
    kcal: '361',
    protein: '12',
    lipid: '8',
    carbo: '58',
  },
  {
    name: '雑炊',
    kcal: '291',
    protein: '7',
    lipid: '3',
    carbo: '57',
  },
  {
    name: 'たまご雑炊',
    kcal: '290',
    protein: '8',
    lipid: '3',
    carbo: '54',
  },
  {
    name: 'キムチ雑炊',
    kcal: '306',
    protein: '8',
    lipid: '3',
    carbo: '60',
  },
  {
    name: 'カニ雑炊',
    kcal: '360',
    protein: '20',
    lipid: '5',
    carbo: '54',
  },
  {
    name: '親子丼',
    kcal: '673',
    protein: '24',
    lipid: '15',
    carbo: '104',
  },
  {
    name: '海鮮丼',
    kcal: '648',
    protein: '31',
    lipid: '8',
    carbo: '106',
  },
  {
    name: 'カツ丼',
    kcal: '896',
    protein: '31',
    lipid: '34',
    carbo: '110',
  },
  {
    name: '牛丼',
    kcal: '735',
    protein: '22',
    lipid: '20',
    carbo: '105',
  },
  {
    name: '豚丼',
    kcal: '874',
    protein: '19',
    lipid: '41',
    carbo: '99',
  },
  {
    name: 'ビビンバ',
    kcal: '753',
    protein: '17',
    lipid: '28',
    carbo: '102',
  },
  {
    name: 'クッパ',
    kcal: '496',
    protein: '19',
    lipid: '14',
    carbo: '71',
  },
  {
    name: 'ひつまぶし',
    kcal: '674',
    protein: '26',
    lipid: '18',
    carbo: '98',
  },
  {
    name: 'チキンカツ丼',
    kcal: '835',
    protein: '28',
    lipid: '28',
    carbo: '108',
  },
  {
    name: 'いくらご飯',
    kcal: '557',
    protein: '23',
    lipid: '9',
    carbo: '93',
  },
  {
    name: 'チャーシュー丼',
    kcal: '595',
    protein: '14',
    lipid: '11',
    carbo: '102',
  },
  {
    name: '中華丼',
    kcal: '698',
    protein: '19',
    lipid: '19',
    carbo: '107',
  },
  {
    name: '鰻重',
    kcal: '772',
    protein: '31',
    lipid: '23',
    carbo: '104',
  },
  {
    name: '鉄火丼',
    kcal: '547',
    protein: '28',
    lipid: '2',
    carbo: '99',
  },
  {
    name: '天丼',
    kcal: '838',
    protein: '23',
    lipid: '27',
    carbo: '119',
  },
  {
    name: 'イカ天丼',
    kcal: '723',
    protein: '20',
    lipid: '12',
    carbo: '128',
  },
  {
    name: '鶏天丼',
    kcal: '799',
    protein: '32',
    lipid: '18',
    carbo: '120',
  },
  {
    name: 'えび天丼',
    kcal: '703',
    protein: '19',
    lipid: '13',
    carbo: '121',
  },
  {
    name: '鶏マヨ丼',
    kcal: '791',
    protein: '25',
    lipid: '25',
    carbo: '110',
  },
  {
    name: '釜めし',
    kcal: '333',
    protein: '11',
    lipid: '5',
    carbo: '58',
  },
  {
    name: '生しらす丼',
    kcal: '511',
    protein: '25',
    lipid: '2',
    carbo: '93',
  },
  {
    name: '麻婆丼',
    kcal: '732',
    protein: '25',
    lipid: '22',
    carbo: '103',
  },
  {
    name: 'まぐろアボカド丼',
    kcal: '716',
    protein: '28',
    lipid: '20',
    carbo: '101',
  },
  {
    name: 'サーモンアボカド丼',
    kcal: '665',
    protein: '17',
    lipid: '19',
    carbo: '103',
  },
  {
    name: 'まぐろのユッケ丼',
    kcal: '626',
    protein: '27',
    lipid: '14',
    carbo: '92',
  },
  {
    name: 'まぐろ山かけ丼',
    kcal: '549',
    protein: '26',
    lipid: '2',
    carbo: '102',
  },
  {
    name: '味噌かつ丼',
    kcal: '1039',
    protein: '33',
    lipid: '38',
    carbo: '132',
  },
  {
    name: '麦とろご飯',
    kcal: '323',
    protein: '7',
    lipid: '1',
    carbo: '70',
  },
  {
    name: '焼鳥丼',
    kcal: '732',
    protein: '22',
    lipid: '22',
    carbo: '105',
  },
  {
    name: 'すき焼き丼',
    kcal: '664',
    protein: '28',
    lipid: '13',
    carbo: '102',
  },
  {
    name: '焼肉丼',
    kcal: '678',
    protein: '27',
    lipid: '14',
    carbo: '105',
  },
  {
    name: 'ステーキ丼',
    kcal: '890',
    protein: '29',
    lipid: '37',
    carbo: '101',
  },
  {
    name: 'ローストビーフ丼',
    kcal: '686',
    protein: '30',
    lipid: '13',
    carbo: '103',
  },
  {
    name: 'ソースカツ丼',
    kcal: '940',
    protein: '30',
    lipid: '37',
    carbo: '118',
  },
  {
    name: 'ロコモコ',
    kcal: '766',
    protein: '28',
    lipid: '21',
    carbo: '112',
  },
  {
    name: 'ねぎとろ丼',
    kcal: '747',
    protein: '24',
    lipid: '24',
    carbo: '102',
  },
  {
    name: '麻婆なす丼',
    kcal: '677',
    protein: '14',
    lipid: '21',
    carbo: '102',
  },
  {
    name: 'ヒレカツ丼',
    kcal: '797',
    protein: '32',
    lipid: '20',
    carbo: '112',
  },
  {
    name: '味噌汁（わかめと豆腐）',
    kcal: '44',
    protein: '4',
    lipid: '2',
    carbo: '4',
  },
  {
    name: '味噌汁（しじみ）',
    kcal: '35',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（大根と油揚げ）',
    kcal: '51',
    protein: '3',
    lipid: '3',
    carbo: '4',
  },
  {
    name: '味噌汁（あさりとネギ）',
    kcal: '34',
    protein: '3',
    lipid: '1',
    carbo: '3',
  },
  {
    name: '味噌汁（あさりとわかめ）',
    kcal: '34',
    protein: '4',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（小松菜と油揚げ）',
    kcal: '52',
    protein: '4',
    lipid: '3',
    carbo: '4',
  },
  {
    name: '味噌汁（玉ねぎとじゃがいも）',
    kcal: '86',
    protein: '4',
    lipid: '1',
    carbo: '17',
  },
  {
    name: '味噌汁（小松菜と千切り大根）',
    kcal: '37',
    protein: '3',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（根菜）',
    kcal: '63',
    protein: '3',
    lipid: '1',
    carbo: '12',
  },
  {
    name: '味噌汁（さつまいも）',
    kcal: '62',
    protein: '2',
    lipid: '1',
    carbo: '11',
  },
  {
    name: '味噌汁（里芋と大豆）',
    kcal: '80',
    protein: '5',
    lipid: '2',
    carbo: '11',
  },
  {
    name: '味噌汁（豆腐）',
    kcal: '47',
    protein: '4',
    lipid: '2',
    carbo: '4',
  },
  {
    name: '味噌汁（豆腐とまいたけ）',
    kcal: '69',
    protein: '6',
    lipid: '3',
    carbo: '6',
  },
  {
    name: '味噌汁（ほうれん草とえのき）',
    kcal: '33',
    protein: '3',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（モロヘイヤとみょうが）',
    kcal: '41',
    protein: '3',
    lipid: '1',
    carbo: '6',
  },
  {
    name: '味噌汁（わかめとしめじ）',
    kcal: '29',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（玉ねぎ）',
    kcal: '33',
    protein: '2',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（豆腐とネギ）',
    kcal: '47',
    protein: '4',
    lipid: '2',
    carbo: '5',
  },
  {
    name: '味噌汁（長ねぎ）',
    kcal: '30',
    protein: '2',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（なす）',
    kcal: '32',
    protein: '2',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（なす）',
    kcal: '32',
    protein: '2',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（なめこ）',
    kcal: '29',
    protein: '2',
    lipid: '1',
    carbo: '4',
  },
  {
    name: '味噌汁（白菜と油揚げ）',
    kcal: '53',
    protein: '4',
    lipid: '3',
    carbo: '5',
  },
  {
    name: '味噌汁（ほうれん草と麩）',
    kcal: '35',
    protein: '3',
    lipid: '1',
    carbo: '5',
  },
  {
    name: '味噌汁（もやし）',
    kcal: '30',
    protein: '3',
    lipid: '1',
    carbo: '4',
  },
  {
    name: 'コンソメスープ',
    kcal: '15',
    protein: '0',
    lipid: '0',
    carbo: '3',
  },
  {
    name: 'たまごスープ',
    kcal: '45',
    protein: '3',
    lipid: '2',
    carbo: '4',
  },
  {
    name: 'わかめスープ',
    kcal: '14',
    protein: '2',
    lipid: '1',
    carbo: '1',
  },
  {
    name: '野菜スープ',
    kcal: '14',
    protein: '1',
    lipid: '0',
    carbo: '3',
  },
  {
    name: '具だくさん野菜スープ',
    kcal: '100',
    protein: '2',
    lipid: '6',
    carbo: '11',
  },
  {
    name: 'かぼちゃのポタージュ',
    kcal: '147',
    protein: '5',
    lipid: '4',
    carbo: '23',
  },
  {
    name: 'ミネストローネ',
    kcal: '104',
    protein: '3',
    lipid: '4',
    carbo: '14',
  },
  {
    name: 'ふかひれスープ',
    kcal: '56',
    protein: '8',
    lipid: '2',
    carbo: '2',
  },
  {
    name: 'デトックススープ',
    kcal: '72',
    protein: '3',
    lipid: '1',
    carbo: '16',
  },
  {
    name: 'サンラータン',
    kcal: '71',
    protein: '8',
    lipid: '3',
    carbo: '3',
  },
  {
    name: 'コーンポタージュ',
    kcal: '145',
    protein: '6',
    lipid: '6',
    carbo: '17',
  },
  {
    name: 'サムゲタン（参鶏湯）',
    kcal: '247',
    protein: '22',
    lipid: '10',
    carbo: '15',
  },
  {
    name: 'トムヤムクン',
    kcal: '156',
    protein: '15',
    lipid: '6',
    carbo: '7',
  },
  {
    name: '春雨スープ',
    kcal: '67',
    protein: '4',
    lipid: '2',
    carbo: '7',
  },
  {
    name: 'スープ餃子',
    kcal: '158',
    protein: '6',
    lipid: '8',
    carbo: '17',
  }
])
